artifact_location: /Users/antonabyzov/Projects/github/specweave/runs/mlflow/117986000268436421
creation_time: 1762277304486
experiment_id: '117986000268436421'
last_update_time: 1762277304486
lifecycle_stage: active
name: /Users/antonabyzov/Projects/github/specweave/.specweave/test-runs/ml-pipeline/2025-11-04T17-28-07-698Z
