#!/usr/bin/env node
/**
 * Generate the bash / zsh / fish completions from bin/specweave.js.
 *
 * Run: node scripts/completions/generate.mjs
 * A unit test (tests/unit/cli/completions-sync.test.ts) re-runs this in memory
 * and fails when the checked-in files drift.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseCliCommands } from './parse-cli.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = path.resolve(HERE, '..', '..');
export const BIN_PATH = path.join(REPO_ROOT, 'bin', 'specweave.js');
export const OUT_DIR = HERE;

const HEADER = 'DO NOT EDIT BY HAND - generated by scripts/completions/generate.mjs';

/** Flag words (`--force`, `-f`) a command accepts, deduplicated, help last. */
function flagWords(command) {
  const words = [];
  for (const opt of command.options) {
    for (const token of opt.flags.split(/[\s,]+/)) {
      if (token.startsWith('-') && !words.includes(token)) words.push(token);
    }
  }
  words.push('--help');
  return words;
}

const bashEscape = (s) => s.replace(/"/g, '\\"');
const fishEscape = (s) => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
const zshEscape = (s) => s.replace(/\\/g, '\\\\').replace(/'/g, "'\\''").replace(/:/g, '\\:');
const zshBracket = (s) => zshEscape(s).replace(/\[/g, '\\[').replace(/\]/g, '\\]');

export function generateBash(commands) {
  const visible = commands.filter((c) => !c.hidden);
  const lines = [
    '#!/usr/bin/env bash',
    '#',
    '# Bash completion for SpecWeave CLI',
    `# ${HEADER}`,
    '#',
    '# Installation:',
    '#   source /path/to/specweave.bash',
    '#',
    '',
    '_specweave_completions() {',
    '    local cur prev',
    '    COMPREPLY=()',
    '    cur="${COMP_WORDS[COMP_CWORD]}"',
    '    prev="${COMP_WORDS[COMP_CWORD-1]}"',
    '',
    `    local main_commands="${visible.map((c) => c.name).join(' ')}"`,
    '',
    '    case "${prev}" in',
    '        specweave)',
    '            COMPREPLY=( $(compgen -W "${main_commands}" -- "${cur}") )',
    '            return 0',
    '            ;;',
  ];
  for (const command of visible) {
    const words = command.subcommands.length
      ? command.subcommands.filter((s) => !s.hidden).map((s) => s.name).concat(flagWords(command))
      : flagWords(command);
    lines.push(`        ${command.name})`);
    lines.push('            COMPREPLY=( $(compgen -W "' + bashEscape(words.join(' ')) + '" -- "${cur}") )');
    lines.push('            return 0', '            ;;');
  }
  lines.push(
    '        *)',
    '            COMPREPLY=( $(compgen -W "${main_commands}" -- "${cur}") )',
    '            return 0',
    '            ;;',
    '    esac',
    '}',
    '',
    'complete -F _specweave_completions specweave',
    ''
  );
  return lines.join('\n');
}

export function generateZsh(commands) {
  const visible = commands.filter((c) => !c.hidden);
  const lines = [
    '#compdef specweave',
    '#',
    '# Zsh completion for SpecWeave CLI',
    `# ${HEADER}`,
    '#',
    '# Installation: copy to your fpath as _specweave',
    '#',
    '',
    'local -a commands',
    'commands=(',
  ];
  for (const command of visible) {
    lines.push(`    '${zshEscape(command.name)}:${zshEscape(command.description)}'`);
  }
  lines.push(')', '', '_specweave() {', '    local curcontext="$curcontext" state line', '');
  lines.push("    _arguments -C '1: :->command' '*::arg:->args'", '');
  lines.push('    case $state in', '        command)');
  lines.push("            _describe -t commands 'specweave commands' commands", '            ;;');
  lines.push('        args)', '            case $line[1] in');
  for (const command of visible) {
    lines.push(`                ${command.name})`);
    lines.push('                    _arguments \\');
    const specs = [];
    if (command.subcommands.length) {
      const subs = command.subcommands.filter((s) => !s.hidden).map((s) => s.name).join(' ');
      specs.push(`'1:subcommand:(${subs})'`);
    }
    for (const opt of command.options) {
      const flag = opt.flags.split(/[\s,]+/).find((t) => t.startsWith('--')) || opt.flags.split(/[\s,]+/)[0];
      specs.push(`'${zshEscape(flag)}[${zshBracket(opt.description)}]'`);
    }
    specs.push("'--help[Show help]'");
    lines.push(specs.map((s, i) => `                        ${s}${i === specs.length - 1 ? '' : ' \\'}`).join('\n'));
    lines.push('                    ;;');
  }
  lines.push(
    '            esac',
    '            ;;',
    '    esac',
    '}',
    '',
    '_specweave "$@"',
    ''
  );
  return lines.join('\n');
}

export function generateFish(commands) {
  const visible = commands.filter((c) => !c.hidden);
  const lines = [
    '# Fish completion for SpecWeave CLI',
    `# ${HEADER}`,
    '#',
    '# Installation: cp specweave.fish ~/.config/fish/completions/specweave.fish',
    '#',
    '',
    `set -l commands ${visible.map((c) => c.name).join(' ')}`,
    '',
    '# Disable file completion for specweave',
    'complete -c specweave -f',
    '',
  ];
  for (const command of visible) {
    lines.push(
      `complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a ${command.name} -d "${fishEscape(command.description)}"`
    );
  }
  for (const command of visible) {
    const subs = command.subcommands.filter((s) => !s.hidden);
    if (!subs.length && !command.options.length) continue;
    lines.push('', `# ${command.name}`);
    if (subs.length) {
      lines.push(
        `complete -c specweave -n "__fish_seen_subcommand_from ${command.name}" -a "${subs.map((s) => s.name).join(' ')}" -d "${command.name} subcommand"`
      );
    }
    for (const opt of command.options) {
      const tokens = opt.flags.split(/[\s,]+/).filter((t) => t.startsWith('-'));
      const long = tokens.find((t) => t.startsWith('--'));
      const short = tokens.find((t) => /^-[^-]$/.test(t));
      let spec = `complete -c specweave -n "__fish_seen_subcommand_from ${command.name}"`;
      if (long) spec += ` -l ${long.slice(2)}`;
      if (short) spec += ` -s ${short.slice(1)}`;
      if (!long && !short) continue;
      lines.push(`${spec} -d "${fishEscape(opt.description)}"`);
    }
  }
  lines.push('', '# Global help option', 'complete -c specweave -l help -s h -d "Show help"', '');
  return lines.join('\n');
}

/** @returns {Record<string,string>} filename -> contents */
export function generateAll(binSource) {
  const commands = parseCliCommands(binSource);
  return {
    'specweave.bash': generateBash(commands),
    'specweave.zsh': generateZsh(commands),
    'specweave.fish': generateFish(commands),
  };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const files = generateAll(readFileSync(BIN_PATH, 'utf8'));
  for (const [name, content] of Object.entries(files)) {
    writeFileSync(path.join(OUT_DIR, name), content, 'utf8');
    console.log(`wrote scripts/completions/${name}`);
  }
}
