#!/usr/bin/env bash
#
# Bash completion for SpecWeave CLI
# DO NOT EDIT BY HAND - generated by scripts/completions/generate.mjs
#
# Installation:
#   source /path/to/specweave.bash
#

_specweave_completions() {
    local cur prev
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    local main_commands="init uninstall install scan-skill scan-plugins judge-skill list pause resume abandon complete task verify create-increment handoff next-id archive save status interview decision-log status-line auto auto-status cancel-auto team update-instructions update check-discipline gc qa link-pr branch-name jobs living-docs cache analytics analytics-push lsp commits sync docs refresh-plugins doctor health session hook detect-intent evaluate-completion generate-rubric reflect-stop detect-project resolve-structure export-skills dashboard hooks context get migrate-to-umbrella"

    case "${prev}" in
        specweave)
            COMPREPLY=( $(compgen -W "${main_commands}" -- "${cur}") )
            return 0
            ;;
        init)
            COMPREPLY=( $(compgen -W "-n --name -t --template -a --adapter --tech-stack -l --language -f --force --force-refresh --no-living-docs --full -q --quick --non-interactive --help" -- "${cur}") )
            return 0
            ;;
        uninstall)
            COMPREPLY=( $(compgen -W "--global --keep-data --dry-run -f --force --help" -- "${cur}") )
            return 0
            ;;
        install)
            COMPREPLY=( $(compgen -W "-g --global -l --local --help" -- "${cur}") )
            return 0
            ;;
        scan-skill)
            COMPREPLY=( $(compgen -W "--json --help" -- "${cur}") )
            return 0
            ;;
        scan-plugins)
            COMPREPLY=( $(compgen -W "--json --verbose --dir --help" -- "${cur}") )
            return 0
            ;;
        judge-skill)
            COMPREPLY=( $(compgen -W "--json --model --scan-only --help" -- "${cur}") )
            return 0
            ;;
        list)
            COMPREPLY=( $(compgen -W "--installed --help" -- "${cur}") )
            return 0
            ;;
        pause)
            COMPREPLY=( $(compgen -W "-r --reason -f --force --help" -- "${cur}") )
            return 0
            ;;
        resume)
            COMPREPLY=( $(compgen -W "--help" -- "${cur}") )
            return 0
            ;;
        abandon)
            COMPREPLY=( $(compgen -W "-r --reason -f --force --help" -- "${cur}") )
            return 0
            ;;
        complete)
            COMPREPLY=( $(compgen -W "-s --silent -y --yes --skip-validation -r --reason --help" -- "${cur}") )
            return 0
            ;;
        task)
            COMPREPLY=( $(compgen -W "-f --force -e --evidence --run -n --note --all-mine --json --help" -- "${cur}") )
            return 0
            ;;
        verify)
            COMPREPLY=( $(compgen -W "--cmd --json --help" -- "${cur}") )
            return 0
            ;;
        create-increment)
            COMPREPLY=( $(compgen -W "--id --auto-id --name --board --type --priority --project-root --parallel --json --help" -- "${cur}") )
            return 0
            ;;
        handoff)
            COMPREPLY=( $(compgen -W "--reason --summary --next --gotcha --decision --inline --clipboard --non-specweave --out --json --help" -- "${cur}") )
            return 0
            ;;
        next-id)
            COMPREPLY=( $(compgen -W "--project --project-root --name --help" -- "${cur}") )
            return 0
            ;;
        archive)
            COMPREPLY=( $(compgen -W "--keep-last --last --older-than --pattern --archive-completed --no-preserve-active --external --dry-run --help" -- "${cur}") )
            return 0
            ;;
        save)
            COMPREPLY=( $(compgen -W "-i --interactive --dry-run --sync --no-stash --repos --skip-no-remote --all --no-push --force --branch --help" -- "${cur}") )
            return 0
            ;;
        status)
            COMPREPLY=( $(compgen -W "-v --verbose -t --type --help" -- "${cur}") )
            return 0
            ;;
        interview)
            COMPREPLY=( $(compgen -W "--help" -- "${cur}") )
            return 0
            ;;
        decision-log)
            COMPREPLY=( $(compgen -W "--hook --decision --since --limit --json --tail --help" -- "${cur}") )
            return 0
            ;;
        status-line)
            COMPREPLY=( $(compgen -W "--json --clear --config --help" -- "${cur}") )
            return 0
            ;;
        auto)
            COMPREPLY=( $(compgen -W "--dry-run --all-backlog --reset --help" -- "${cur}") )
            return 0
            ;;
        auto-status)
            COMPREPLY=( $(compgen -W "--verbose --json --help" -- "${cur}") )
            return 0
            ;;
        cancel-auto)
            COMPREPLY=( $(compgen -W "--force --help" -- "${cur}") )
            return 0
            ;;
        team)
            COMPREPLY=( $(compgen -W "--mode --no-increment --help" -- "${cur}") )
            return 0
            ;;
        update-instructions)
            COMPREPLY=( $(compgen -W "--dry-run -v --verbose --help" -- "${cur}") )
            return 0
            ;;
        update)
            COMPREPLY=( $(compgen -W "--no-self --no-plugins --all --minimal --check -v --verbose -f --force --help" -- "${cur}") )
            return 0
            ;;
        check-discipline)
            COMPREPLY=( $(compgen -W "-v --verbose --json --project-root --help" -- "${cur}") )
            return 0
            ;;
        gc)
            COMPREPLY=( $(compgen -W "-y --yes --json --project-root --help" -- "${cur}") )
            return 0
            ;;
        qa)
            COMPREPLY=( $(compgen -W "--quick --pre --gate --full --ci --no-ai --silent --export -f --force -v --verbose --help" -- "${cur}") )
            return 0
            ;;
        link-pr)
            COMPREPLY=( $(compgen -W "--branch --help" -- "${cur}") )
            return 0
            ;;
        branch-name)
            COMPREPLY=( $(compgen -W "--help" -- "${cur}") )
            return 0
            ;;
        jobs)
            COMPREPLY=( $(compgen -W "--all --id --logs --follow --kill --resume --help" -- "${cur}") )
            return 0
            ;;
        living-docs)
            COMPREPLY=( $(compgen -W "--resume --depth --priority --sources --depends-on --foreground --force --full-scan --help" -- "${cur}") )
            return 0
            ;;
        cache)
            COMPREPLY=( $(compgen -W "--rebuild --status --clear --quiet --debug --help" -- "${cur}") )
            return 0
            ;;
        analytics)
            COMPREPLY=( $(compgen -W "--export --since --type --json --limit --help" -- "${cur}") )
            return 0
            ;;
        analytics-push)
            COMPREPLY=( $(compgen -W "--plugin --json --silent --help" -- "${cur}") )
            return 0
            ;;
        lsp)
            COMPREPLY=( $(compgen -W "refs def hover symbols search warmup status setup --help" -- "${cur}") )
            return 0
            ;;
        commits)
            COMPREPLY=( $(compgen -W "--help" -- "${cur}") )
            return 0
            ;;
        sync)
            COMPREPLY=( $(compgen -W "push pull status setup --help" -- "${cur}") )
            return 0
            ;;
        docs)
            COMPREPLY=( $(compgen -W "preview build validate public kill status sync --help" -- "${cur}") )
            return 0
            ;;
        refresh-plugins)
            COMPREPLY=( $(compgen -W "--all --plugin -q --quiet -f --force -v --verbose --help" -- "${cur}") )
            return 0
            ;;
        doctor)
            COMPREPLY=( $(compgen -W "--verbose --json --quick --skip-external --fix --fix-status --help" -- "${cur}") )
            return 0
            ;;
        health)
            COMPREPLY=( $(compgen -W "--json --verbose --help" -- "${cur}") )
            return 0
            ;;
        session)
            COMPREPLY=( $(compgen -W "start end --help" -- "${cur}") )
            return 0
            ;;
        hook)
            COMPREPLY=( $(compgen -W "--help" -- "${cur}") )
            return 0
            ;;
        detect-intent)
            COMPREPLY=( $(compgen -W "--install --silent --file --help" -- "${cur}") )
            return 0
            ;;
        evaluate-completion)
            COMPREPLY=( $(compgen -W "--model --timeout --silent --help" -- "${cur}") )
            return 0
            ;;
        generate-rubric)
            COMPREPLY=( $(compgen -W "--refresh --silent --help" -- "${cur}") )
            return 0
            ;;
        reflect-stop)
            COMPREPLY=( $(compgen -W "-s --silent -m --model --migrate --help" -- "${cur}") )
            return 0
            ;;
        detect-project)
            COMPREPLY=( $(compgen -W "--name --description --install --silent --help" -- "${cur}") )
            return 0
            ;;
        resolve-structure)
            COMPREPLY=( $(compgen -W "--help" -- "${cur}") )
            return 0
            ;;
        export-skills)
            COMPREPLY=( $(compgen -W "-o --output -p --plugin -s --skill --dry-run --validate -v --verbose --help" -- "${cur}") )
            return 0
            ;;
        dashboard)
            COMPREPLY=( $(compgen -W "-p --port --no-browser --help" -- "${cur}") )
            return 0
            ;;
        hooks)
            COMPREPLY=( $(compgen -W "log --help" -- "${cur}") )
            return 0
            ;;
        context)
            COMPREPLY=( $(compgen -W "projects --help" -- "${cur}") )
            return 0
            ;;
        get)
            COMPREPLY=( $(compgen -W "--branch --prefix --role --no-init --yes --all --pattern --limit --no-archived --no-forks --help" -- "${cur}") )
            return 0
            ;;
        migrate-to-umbrella)
            COMPREPLY=( $(compgen -W "--help" -- "${cur}") )
            return 0
            ;;
        *)
            COMPREPLY=( $(compgen -W "${main_commands}" -- "${cur}") )
            return 0
            ;;
    esac
}

complete -F _specweave_completions specweave
