#compdef specweave
#
# Zsh completion for SpecWeave CLI
# DO NOT EDIT BY HAND - generated by scripts/completions/generate.mjs
#
# Installation: copy to your fpath as _specweave
#

local -a commands
commands=(
    'init:Initialize a new SpecWeave project'
    'uninstall:Remove SpecWeave from the current project'
    'install:Install agents/skills to .claude/ or ~/.claude/'
    'scan-skill:Scan a skill file for security issues (Tier 1 pattern scanning)'
    'scan-plugins:Batch-scan all plugin SKILL.md files for security issues (Gen Agent Trust Hub categories)'
    'judge-skill:Judge a skill file for security threats (Tier 1 patterns + Tier 2 LLM)'
    'list:List available and installed components'
    'pause:Pause an active increment'
    'start:Start a planned/backlog/paused increment (status -> active)'
    'resume:Resume a paused, abandoned or not-yet-started increment'
    'abandon:Abandon an increment'
    'complete:Complete one or more increments (triggers GitHub/JIRA/ADO sync)'
    'task:Task ledger\: list | next | claim | done | release | block | skip | render | whoami'
    'verify:'
    'create-increment:Create increment template files (metadata.json, spec.md, tasks.md). Short form\: specweave create-increment "Add login form"'
    'handoff:Write a portable, secret-scrubbed work-handoff doc + diff so you can resume in another AI tool'
    'next-id:Return the next available increment number. Prefer\: create-increment --auto-id'
    'archive:Archive completed increments and sync living docs (project-specific folders)'
    'save:Smart save - auto-generate commit message, sync with remote, commit and push'
    'status:Show increment status overview (alias\: progress)'
    'interview:Manage Deep Interview Mode for increment planning'
    'decision-log:Query structured decision logs from hooks'
    'status-line:Display current increment status line'
    'auto:Start autonomous execution (stop hook feedback loop)'
    'auto-status:Check auto session status and progress'
    'cancel-auto:Cancel running auto session'
    'team:Launch Claude Code with agent teams (tmux/iTerm2 split panes)'
    'update-instructions:Update CLAUDE.md and AGENTS.md with smart merge (preserves user content)'
    'update:Update SpecWeave\: CLI, instructions, config, AND plugins (default)'
    'check-discipline:Report increment status counts, advisory WIP note and metadata consistency'
    'gc:Purge stale .specweave/state files (dry-run; --yes to delete), report .worktrees size and nested .specweave dirs'
    'qa:Run quality assessment on an increment'
    'link-pr:Link a pull request to external tickets (JIRA, ADO)'
    'branch-name:Output the computed branch name for an increment (with optional JIRA/ADO ticket key)'
    'jobs:Monitor and manage background jobs (imports, cloning, sync)'
    'living-docs:Launch or resume Living Docs Builder independently'
    'cache:Manage dashboard cache for instant status commands'
    'analytics:Show usage analytics dashboard (commands, skills, agents)'
    'analytics-push:Record a skill or agent analytics event (replaces PostToolUse analytics hook)'
    'lsp:LSP code intelligence (refs, def, hover, symbols, search)'
    'commits:Display the last 2 git commits'
    'sync:Sync increments with GitHub, Jira or Azure DevOps\: push | pull | status | setup'
    'docs:Documentation preview, build, and validation (works in any SpecWeave project)'
    'refresh-plugins:Refresh SpecWeave plugins (core only by default, use --all for everything)'
    'doctor:Run comprehensive health check on SpecWeave project'
    'health:Quick deployment health check (config, plugins, sync connectivity)'
    'session:Session lifecycle management (start, end)'
    'hook:Handle Claude Code hook events (internal)'
    'detect-intent:Detect SpecWeave intent from a prompt and optionally install plugins'
    'evaluate-completion:Evaluate whether an auto mode session should be considered complete'
    'generate-rubric:Generate or refresh the AC-tied rubric.md quality contract at the increment root'
    'reflect-stop:Extract learnings from session transcript (called by stop hook)'
    'detect-project:Detect project type from files and suggest plugins to install'
    'resolve-structure:[REMOVED] All workspaces now use the repositories/ structure'
    'export-skills:Export SpecWeave skills to Agent Skills open standard format (agentskills.io)'
    'dashboard:Launch real-time observability dashboard in browser'
    'hooks:'
    'context:Show SpecWeave workspace context'
    'get:Clone and register an existing repository into the workspace'
    'migrate-to-umbrella:[REMOVED] Use specweave get to add repositories'
)

_specweave() {
    local curcontext="$curcontext" state line

    _arguments -C '1: :->command' '*::arg:->args'

    case $state in
        command)
            _describe -t commands 'specweave commands' commands
            ;;
        args)
            case $line[1] in
                init)
                    _arguments \
                        '--name[Project name (alternative to positional argument)]' \
                        '--template[Project template (saas, api, fullstack)]' \
                        '--adapter[AI tool adapter (claude, cursor, copilot, generic)]' \
                        '--tech-stack[Technology stack (nodejs, python, etc.)]' \
                        '--language[Language for generated content (en, ru, es, zh, de, fr, ja, ko, pt)]' \
                        '--force[Force fresh start (non-interactive, removes existing .specweave)]' \
                        '--force-refresh[Force marketplace refresh (skip cache, always pull latest)]' \
                        '--no-living-docs[Skip living docs builder setup]' \
                        '--full[Install all plugins (skip lazy loading, longer init but all skills available immediately)]' \
                        '--quick[Quick mode\: skip all prompts, use sensible defaults (local git, no external tools, minimal setup)]' \
                        '--non-interactive[Alias for --quick (skip all prompts)]' \
                        '--help[Show help]'
                    ;;
                uninstall)
                    _arguments \
                        '--global[Also clean global agent directories and plugin cache]' \
                        '--keep-data[Archive .specweave/ instead of deleting]' \
                        '--dry-run[Show what would be removed without deleting]' \
                        '--force[Skip confirmation prompt]' \
                        '--help[Show help]'
                    ;;
                install)
                    _arguments \
                        '--global[Install globally to ~/.claude/]' \
                        '--local[Install locally to .claude/ (default)]' \
                        '--help[Show help]'
                    ;;
                scan-skill)
                    _arguments \
                        '--json[Output results as JSON]' \
                        '--help[Show help]'
                    ;;
                scan-plugins)
                    _arguments \
                        '--json[Output results as JSON for CI integration]' \
                        '--verbose[Show per-skill reports in addition to batch summary]' \
                        '--dir[Path to plugins directory (default\: ./plugins)]' \
                        '--help[Show help]'
                    ;;
                judge-skill)
                    _arguments \
                        '--json[Output results as JSON]' \
                        '--model[LLM model to use (e.g., sonnet, opus)]' \
                        '--scan-only[Run Tier 1 only, skip LLM analysis]' \
                        '--help[Show help]'
                    ;;
                list)
                    _arguments \
                        '--installed[Show only installed components]' \
                        '--help[Show help]'
                    ;;
                pause)
                    _arguments \
                        '--reason[Reason for pausing]' \
                        '--force[Force pause (update reason if already paused)]' \
                        '--help[Show help]'
                    ;;
                start)
                    _arguments \
                        '--help[Show help]'
                    ;;
                resume)
                    _arguments \
                        '--help[Show help]'
                    ;;
                abandon)
                    _arguments \
                        '--reason[Reason for abandoning]' \
                        '--force[Force abandon (skip confirmation)]' \
                        '--help[Show help]'
                    ;;
                complete)
                    _arguments \
                        '--silent[Silent mode (for auto mode stop hook)]' \
                        '--yes[Assume yes (silent confirmation)]' \
                        '--skip-validation[Skip quality gate validation (DANGEROUS)]' \
                        '--reason[Close without a passing reports/verify.json (stored as metadata.closeReason)]' \
                        '--all[Close every active increment whose tasks are all done or skipped (requires --reason)]' \
                        '--help[Show help]'
                    ;;
                task)
                    _arguments \
                        '--force[Override a live claim, unmet deps or a Files overlap]' \
                        '--evidence[Evidence for `done` (commit sha, test output)]' \
                        '--run[Run <cmd> through the OS shell; exit 0 required, output stored as evidence]' \
                        '--note[Note (alias of --reason)]' \
                        '--reason[Reason (required for skip / block)]' \
                        '--all-mine[With `release`\: release every task claimed by this agent]' \
                        '--json[Machine-readable output]' \
                        '--help[Show help]'
                    ;;
                verify)
                    _arguments \
                        '--cmd[Command to run (repeatable; overrides config/auto-detection)]' \
                        '--json[Print the verify report as JSON]' \
                        '--help[Show help]'
                    ;;
                create-increment)
                    _arguments \
                        '--id[Increment ID (e.g., "0042-my-feature")]' \
                        '--auto-id[Auto-generate next available increment ID (default when --id is absent)]' \
                        '--name[Increment name suffix (defaults to a slug of the title)]' \
                        '--title[Feature title (defaults to the positional argument)]' \
                        '--description[Feature description (defaults to the title)]' \
                        '--project[Project ID (defaults to config project.name, else the folder name)]' \
                        '--board[Board ID for 2-level structures]' \
                        '--type[Increment type (feature, hotfix, bug, refactor, experiment)]' \
                        '--priority[Priority (P1, P2, P3)]' \
                        '--project-root[Override project root directory]' \
                        '--parallel[Opt into 3-agent fan-out planning (default\: single-agent)]' \
                        '--with-plan[Also scaffold plan.md (optional overflow; spec.md carries the Approach)]' \
                        '--planned[Create as "planned" instead of "active" (backlog work; start it with specweave start <id>)]' \
                        '--supersedes[Increment this one replaces (the old one is abandoned with a closeReason)]' \
                        '--parent[Parent increment (recorded as metadata.parent)]' \
                        '--json[Output result as JSON (for programmatic use)]' \
                        '--help[Show help]'
                    ;;
                handoff)
                    _arguments \
                        '--reason[Why you are handing off (e.g. "out of tokens")]' \
                        '--summary[Short summary of where things stand]' \
                        '--next[The exact next step for the resuming agent]' \
                        '--gotcha[A gotcha / warning for the next agent]' \
                        '--decision[A key decision (repeatable)]' \
                        '--inline[Embed the full scrubbed doc body in the paste-prompt (cross-machine resume)]' \
                        '--clipboard[Alias for --inline]' \
                        '--non-specweave[Force the .handoff/ fallback even inside a SpecWeave workspace]' \
                        '--out[Override the doc output path]' \
                        '--json[Output the full result as JSON (for programmatic use)]' \
                        '--help[Show help]'
                    ;;
                next-id)
                    _arguments \
                        '--project[Project ID for per-project collision prevention]' \
                        '--project-root[Override project root directory]' \
                        '--name[Increment name to generate full ID (e.g., "my-feature" → "0042-my-feature")]' \
                        '--help[Show help]'
                    ;;
                archive)
                    _arguments \
                        '--keep-last[Keep last N increments, archive the rest]' \
                        '--last[STRICT\: Keep exactly last N increments by number, ignoring all protections]' \
                        '--older-than[Archive increments older than N days]' \
                        '--pattern[Archive increments matching pattern (regex)]' \
                        '--archive-completed[Archive all completed increments]' \
                        '--no-preserve-active[Allow archiving active/paused increments (dangerous!)]' \
                        '--external[Archive external living docs (FS-XXXE features imported from ADO/JIRA/GitHub)]' \
                        '--dry-run[Preview what would be archived without moving files]' \
                        '--help[Show help]'
                    ;;
                save)
                    _arguments \
                        '--interactive[Interactive mode - ask before each step]' \
                        '--dry-run[Preview without executing]' \
                        '--sync[Sync strategy (rebase, merge, none)]' \
                        '--no-stash[Skip auto-stash]' \
                        '--repos[Only save specific repos (comma-separated)]' \
                        '--skip-no-remote[Skip repos without remotes]' \
                        '--all[Include all repos (even outside umbrella config)]' \
                        '--no-push[Commit but don'\''t push]' \
                        '--force[Force push (requires confirmation)]' \
                        '--branch[Create new branch instead of force pushing]' \
                        '--help[Show help]'
                    ;;
                status)
                    _arguments \
                        '--verbose[Show detailed information]' \
                        '--type[Filter by increment type (feature, hotfix, bug, etc.)]' \
                        '--help[Show help]'
                    ;;
                interview)
                    _arguments \
                        '--help[Show help]'
                    ;;
                decision-log)
                    _arguments \
                        '--hook[Filter by hook name (stop-auto, stop-reflect)]' \
                        '--decision[Filter by decision type (approve, block)]' \
                        '--since[Filter by time window (1h, 24h, 7d)]' \
                        '--limit[Number of entries to show (default\: 20)]' \
                        '--json[Output raw JSON format]' \
                        '--tail[Follow log in real-time (like tail -f)]' \
                        '--help[Show help]'
                    ;;
                status-line)
                    _arguments \
                        '--json[Output JSON format]' \
                        '--clear[Clear status line cache]' \
                        '--config[Path to config file]' \
                        '--help[Show help]'
                    ;;
                auto)
                    _arguments \
                        '--dry-run[Preview without activating]' \
                        '--all-backlog[Activate all backlog items]' \
                        '--reset[Clean up any stale state files]' \
                        '--help[Show help]'
                    ;;
                auto-status)
                    _arguments \
                        '--verbose[Show detailed information]' \
                        '--json[Output as JSON]' \
                        '--help[Show help]'
                    ;;
                cancel-auto)
                    _arguments \
                        '--force[Force cancel without confirmation]' \
                        '--help[Show help]'
                    ;;
                team)
                    _arguments \
                        '--mode[Display mode\: tmux (default) or in-process]' \
                        '--no-increment[Launch without requiring a SpecWeave increment (free-form agent swarm)]' \
                        '--help[Show help]'
                    ;;
                update-instructions)
                    _arguments \
                        '--dry-run[Preview changes without writing]' \
                        '--verbose[Show detailed merge information]' \
                        '--help[Show help]'
                    ;;
                update)
                    _arguments \
                        '--no-self[Skip CLI self-update via npm]' \
                        '--no-plugins[Skip marketplace plugins refresh]' \
                        '--all[Install ALL plugins (not just router)]' \
                        '--minimal[Clean /plugin output (removes marketplace, no lazy loading)]' \
                        '--check[Dry run - show what would change without making changes]' \
                        '--verbose[Show detailed output]' \
                        '--force[Force refresh even if up to date]' \
                        '--help[Show help]'
                    ;;
                check-discipline)
                    _arguments \
                        '--verbose[Show detailed increment information]' \
                        '--json[Output results as JSON]' \
                        '--project-root[Project root directory]' \
                        '--help[Show help]'
                    ;;
                gc)
                    _arguments \
                        '--yes[Actually delete (default is dry-run)]' \
                        '--json[Output as JSON]' \
                        '--project-root[Project root directory]' \
                        '--help[Show help]'
                    ;;
                qa)
                    _arguments \
                        '--quick[Quick mode (default)]' \
                        '--pre[Pre-implementation check]' \
                        '--gate[Quality gate check (comprehensive)]' \
                        '--full[Full multi-agent mode (Phase 3)]' \
                        '--ci[CI mode (exit 1 on FAIL)]' \
                        '--no-ai[Skip AI assessment (rule-based only)]' \
                        '--silent[Minimal output]' \
                        '--export[Export blockers/concerns to tasks.md]' \
                        '--force[Force run even if rule-based fails]' \
                        '--verbose[Show recommendations]' \
                        '--help[Show help]'
                    ;;
                link-pr)
                    _arguments \
                        '--branch[Branch name]' \
                        '--help[Show help]'
                    ;;
                branch-name)
                    _arguments \
                        '--help[Show help]'
                    ;;
                jobs)
                    _arguments \
                        '--all[Show all jobs (including completed)]' \
                        '--id[Show details for specific job]' \
                        '--logs[Show worker log output]' \
                        '--follow[Follow job progress in real-time]' \
                        '--kill[Kill running background job]' \
                        '--resume[Resume paused job]' \
                        '--help[Show help]'
                    ;;
                living-docs)
                    _arguments \
                        '--resume[Resume orphaned/paused job]' \
                        '--depth[Analysis depth\: quick, standard, deep-native, deep-api]' \
                        '--priority[Priority modules (comma-separated)]' \
                        '--sources[Additional doc folders (comma-separated)]' \
                        '--depends-on[Wait for jobs before starting (comma-separated)]' \
                        '--foreground[Run in current session instead of background]' \
                        '--force[Force run even for greenfield projects]' \
                        '--full-scan[Force full deep scan (all phases\: repos, org, arch, inconsistencies, strategy)]' \
                        '--help[Show help]'
                    ;;
                cache)
                    _arguments \
                        '--rebuild[Rebuild cache from increments]' \
                        '--status[Show cache status (default)]' \
                        '--clear[Clear cache]' \
                        '--quiet[Minimal output]' \
                        '--debug[Show debug information]' \
                        '--help[Show help]'
                    ;;
                analytics)
                    _arguments \
                        '--export[Export data (json, csv)]' \
                        '--since[Filter by time range (24h, 7d, 30d)]' \
                        '--type[Filter by event type (command, skill, agent)]' \
                        '--json[Output raw JSON for scripting]' \
                        '--limit[Number of top items to show]' \
                        '--help[Show help]'
                    ;;
                analytics-push)
                    _arguments \
                        '--plugin[Source plugin name]' \
                        '--json[Output as JSON]' \
                        '--silent[Suppress output]' \
                        '--help[Show help]'
                    ;;
                lsp)
                    _arguments \
                        '1:subcommand:(refs def hover symbols search warmup status setup)' \
                        '--help[Show help]'
                    ;;
                commits)
                    _arguments \
                        '--help[Show help]'
                    ;;
                sync)
                    _arguments \
                        '1:subcommand:(push pull status setup)' \
                        '--help[Show help]'
                    ;;
                docs)
                    _arguments \
                        '1:subcommand:(preview build validate public kill status sync)' \
                        '--help[Show help]'
                    ;;
                refresh-plugins)
                    _arguments \
                        '--all[Install ALL plugins (not just core sw)]' \
                        '--plugin[Install a specific plugin by name]' \
                        '--quiet[Suppress output (for use by hooks)]' \
                        '--force[Force reinstall (skip hash check)]' \
                        '--verbose[Show skipped plugins]' \
                        '--help[Show help]'
                    ;;
                doctor)
                    _arguments \
                        '--verbose[Show detailed output for each check]' \
                        '--json[Output as JSON]' \
                        '--quick[Skip slow checks (network, hook execution)]' \
                        '--skip-external[Skip external tool connectivity checks]' \
                        '--fix[Apply inline fixes (remove ghost files, stale cache, update lockfile hashes)]' \
                        '--fix-status[Fix metadata.json <-> spec.md status desyncs (formerly sw\:sync-status)]' \
                        '--help[Show help]'
                    ;;
                health)
                    _arguments \
                        '--json[Output as JSON for CI/CD pipelines]' \
                        '--verbose[Show detailed output]' \
                        '--help[Show help]'
                    ;;
                session)
                    _arguments \
                        '1:subcommand:(start end)' \
                        '--help[Show help]'
                    ;;
                hook)
                    _arguments \
                        '--help[Show help]'
                    ;;
                detect-intent)
                    _arguments \
                        '--install[Also install detected plugins after detection]' \
                        '--silent[Silent mode - no stdout output (for hooks)]' \
                        '--file[Read prompt from file instead of argument (avoids shell escaping issues)]' \
                        '--help[Show help]'
                    ;;
                evaluate-completion)
                    _arguments \
                        '--model[Model for LLM evaluation\: haiku or sonnet (default\: sonnet)]' \
                        '--timeout[Timeout in milliseconds (default\: 45000)]' \
                        '--silent[Minimal output]' \
                        '--help[Show help]'
                    ;;
                generate-rubric)
                    _arguments \
                        '--refresh[Regenerate from current ACs, overwriting an existing non-template rubric]' \
                        '--silent[Minimal output]' \
                        '--help[Show help]'
                    ;;
                reflect-stop)
                    _arguments \
                        '--silent[Silent mode - output JSON only]' \
                        '--model[Model to use (haiku, sonnet, opus)]' \
                        '--migrate[Run migration of old memory files first]' \
                        '--help[Show help]'
                    ;;
                detect-project)
                    _arguments \
                        '--name[Increment name for legacy name-based detection]' \
                        '--description[Description for legacy name-based detection]' \
                        '--install[Also install detected plugins after detection]' \
                        '--silent[Silent mode - no stdout output (for hooks)]' \
                        '--help[Show help]'
                    ;;
                resolve-structure)
                    _arguments \
                        '--help[Show help]'
                    ;;
                export-skills)
                    _arguments \
                        '--output[Output directory (default\: .agent-skills)]' \
                        '--plugin[Export specific plugin only]' \
                        '--skill[Export specific skill only]' \
                        '--dry-run[Preview without writing files]' \
                        '--validate[Validate output against Agent Skills spec]' \
                        '--verbose[Show detailed output]' \
                        '--help[Show help]'
                    ;;
                dashboard)
                    _arguments \
                        '--port[Port number (default\: 3456)]' \
                        '--no-browser[Do not open browser automatically]' \
                        '--help[Show help]'
                    ;;
                hooks)
                    _arguments \
                        '1:subcommand:(log)' \
                        '--help[Show help]'
                    ;;
                context)
                    _arguments \
                        '1:subcommand:(projects)' \
                        '--help[Show help]'
                    ;;
                get)
                    _arguments \
                        '--branch[Clone a specific branch]' \
                        '--prefix[User story prefix (default\: first 3 chars uppercase)]' \
                        '--role[Repository role (frontend, backend, mobile, infra, shared)]' \
                        '--no-init[Skip specweave init on cloned repo]' \
                        '--yes[Skip confirmation prompts]' \
                        '--all[Clone all repositories in an org (source is org name)]' \
                        '--pattern[Filter repos by glob pattern, e.g. "service-*" (use with --all or org/* source)]' \
                        '--limit[Max repos to fetch in bulk mode (default\: 1000)]' \
                        '--no-archived[Skip archived repositories in bulk mode]' \
                        '--no-forks[Skip forked repositories in bulk mode]' \
                        '--help[Show help]'
                    ;;
                migrate-to-umbrella)
                    _arguments \
                        '--help[Show help]'
                    ;;
            esac
            ;;
    esac
}

_specweave "$@"
