# Fish completion for SpecWeave CLI
# DO NOT EDIT BY HAND - generated by scripts/completions/generate.mjs
#
# Installation: cp specweave.fish ~/.config/fish/completions/specweave.fish
#

set -l commands init uninstall install scan-skill scan-plugins judge-skill list pause resume abandon complete task verify create-increment handoff next-id archive save status interview decision-log status-line auto auto-status cancel-auto team update-instructions update check-discipline gc qa link-pr branch-name jobs living-docs cache analytics analytics-push lsp commits sync docs refresh-plugins doctor health session hook detect-intent evaluate-completion generate-rubric detect-project resolve-structure export-skills dashboard hooks context get migrate-to-umbrella

# Disable file completion for specweave
complete -c specweave -f

complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a init -d "Initialize a new SpecWeave project"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a uninstall -d "Remove SpecWeave from the current project"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a install -d "Install agents/skills to .claude/ or ~/.claude/"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a scan-skill -d "Scan a skill file for security issues (Tier 1 pattern scanning)"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a scan-plugins -d "Batch-scan all plugin SKILL.md files for security issues (Gen Agent Trust Hub categories)"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a judge-skill -d "Judge a skill file for security threats (Tier 1 patterns + Tier 2 LLM)"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a list -d "List available and installed components"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a pause -d "Pause an active increment"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a resume -d "Resume a paused or abandoned increment"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a abandon -d "Abandon an increment"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a complete -d "Complete one or more increments (triggers GitHub/JIRA/ADO sync)"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a task -d "Task ledger: list | next | claim | done | release | block | skip | render | whoami"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a verify -d ""
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a create-increment -d "Create increment template files (metadata.json, spec.md, tasks.md). Short form: specweave create-increment \"Add login form\""
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a handoff -d "Write a portable, secret-scrubbed work-handoff doc + diff so you can resume in another AI tool"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a next-id -d "Return the next available increment number. Prefer: create-increment --auto-id"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a archive -d "Archive completed increments and sync living docs (project-specific folders)"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a save -d "Smart save - auto-generate commit message, sync with remote, commit and push"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a status -d "Show increment status overview (alias: progress)"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a interview -d "Manage Deep Interview Mode for increment planning"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a decision-log -d "Query structured decision logs from hooks"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a status-line -d "Display current increment status line"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a auto -d "Start autonomous execution (stop hook feedback loop)"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a auto-status -d "Check auto session status and progress"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a cancel-auto -d "Cancel running auto session"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a team -d "Launch Claude Code with agent teams (tmux/iTerm2 split panes)"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a update-instructions -d "Update CLAUDE.md and AGENTS.md with smart merge (preserves user content)"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a update -d "Update SpecWeave: CLI, instructions, config, AND plugins (default)"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a check-discipline -d "Report increment status counts, advisory WIP note and metadata consistency"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a gc -d "Purge stale .specweave/state files (dry-run; --yes to delete), report .worktrees size and nested .specweave dirs"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a qa -d "Run quality assessment on an increment"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a link-pr -d "Link a pull request to external tickets (JIRA, ADO)"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a branch-name -d "Output the computed branch name for an increment (with optional JIRA/ADO ticket key)"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a jobs -d "Monitor and manage background jobs (imports, cloning, sync)"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a living-docs -d "Launch or resume Living Docs Builder independently"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a cache -d "Manage dashboard cache for instant status commands"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a analytics -d "Show usage analytics dashboard (commands, skills, agents)"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a analytics-push -d "Record a skill or agent analytics event (replaces PostToolUse analytics hook)"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a lsp -d "LSP code intelligence (refs, def, hover, symbols, search)"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a commits -d "Display the last 2 git commits"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a sync -d "Sync increments with GitHub, Jira or Azure DevOps: push | pull | status | setup"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a docs -d "Documentation preview, build, and validation (works in any SpecWeave project)"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a refresh-plugins -d "Refresh SpecWeave plugins (core only by default, use --all for everything)"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a doctor -d "Run comprehensive health check on SpecWeave project"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a health -d "Quick deployment health check (config, plugins, sync connectivity)"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a session -d "Session lifecycle management (start, end)"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a hook -d "Handle Claude Code hook events (internal)"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a detect-intent -d "Detect SpecWeave intent from a prompt and optionally install plugins"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a evaluate-completion -d "Evaluate whether an auto mode session should be considered complete"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a generate-rubric -d "Generate or refresh the AC-tied rubric.md quality contract at the increment root"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a detect-project -d "Detect project type from files and suggest plugins to install"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a resolve-structure -d "[REMOVED] All workspaces now use the repositories/ structure"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a export-skills -d "Export SpecWeave skills to Agent Skills open standard format (agentskills.io)"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a dashboard -d "Launch real-time observability dashboard in browser"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a hooks -d ""
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a context -d "Show SpecWeave workspace context"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a get -d "Clone and register an existing repository into the workspace"
complete -c specweave -n "not __fish_seen_subcommand_from $commands" -a migrate-to-umbrella -d "[REMOVED] Use specweave get to add repositories"

# init
complete -c specweave -n "__fish_seen_subcommand_from init" -l name -s n -d "Project name (alternative to positional argument)"
complete -c specweave -n "__fish_seen_subcommand_from init" -l template -s t -d "Project template (saas, api, fullstack)"
complete -c specweave -n "__fish_seen_subcommand_from init" -l adapter -s a -d "AI tool adapter (claude, cursor, copilot, generic)"
complete -c specweave -n "__fish_seen_subcommand_from init" -l tech-stack -d "Technology stack (nodejs, python, etc.)"
complete -c specweave -n "__fish_seen_subcommand_from init" -l language -s l -d "Language for generated content (en, ru, es, zh, de, fr, ja, ko, pt)"
complete -c specweave -n "__fish_seen_subcommand_from init" -l force -s f -d "Force fresh start (non-interactive, removes existing .specweave)"
complete -c specweave -n "__fish_seen_subcommand_from init" -l force-refresh -d "Force marketplace refresh (skip cache, always pull latest)"
complete -c specweave -n "__fish_seen_subcommand_from init" -l no-living-docs -d "Skip living docs builder setup"
complete -c specweave -n "__fish_seen_subcommand_from init" -l full -d "Install all plugins (skip lazy loading, longer init but all skills available immediately)"
complete -c specweave -n "__fish_seen_subcommand_from init" -l quick -s q -d "Quick mode: skip all prompts, use sensible defaults (local git, no external tools, minimal setup)"
complete -c specweave -n "__fish_seen_subcommand_from init" -l non-interactive -d "Alias for --quick (skip all prompts)"

# uninstall
complete -c specweave -n "__fish_seen_subcommand_from uninstall" -l global -d "Also clean global agent directories and plugin cache"
complete -c specweave -n "__fish_seen_subcommand_from uninstall" -l keep-data -d "Archive .specweave/ instead of deleting"
complete -c specweave -n "__fish_seen_subcommand_from uninstall" -l dry-run -d "Show what would be removed without deleting"
complete -c specweave -n "__fish_seen_subcommand_from uninstall" -l force -s f -d "Skip confirmation prompt"

# install
complete -c specweave -n "__fish_seen_subcommand_from install" -l global -s g -d "Install globally to ~/.claude/"
complete -c specweave -n "__fish_seen_subcommand_from install" -l local -s l -d "Install locally to .claude/ (default)"

# scan-skill
complete -c specweave -n "__fish_seen_subcommand_from scan-skill" -l json -d "Output results as JSON"

# scan-plugins
complete -c specweave -n "__fish_seen_subcommand_from scan-plugins" -l json -d "Output results as JSON for CI integration"
complete -c specweave -n "__fish_seen_subcommand_from scan-plugins" -l verbose -d "Show per-skill reports in addition to batch summary"
complete -c specweave -n "__fish_seen_subcommand_from scan-plugins" -l dir -d "Path to plugins directory (default: ./plugins)"

# judge-skill
complete -c specweave -n "__fish_seen_subcommand_from judge-skill" -l json -d "Output results as JSON"
complete -c specweave -n "__fish_seen_subcommand_from judge-skill" -l model -d "LLM model to use (e.g., sonnet, opus)"
complete -c specweave -n "__fish_seen_subcommand_from judge-skill" -l scan-only -d "Run Tier 1 only, skip LLM analysis"

# list
complete -c specweave -n "__fish_seen_subcommand_from list" -l installed -d "Show only installed components"

# pause
complete -c specweave -n "__fish_seen_subcommand_from pause" -l reason -s r -d "Reason for pausing"
complete -c specweave -n "__fish_seen_subcommand_from pause" -l force -s f -d "Force pause (update reason if already paused)"

# abandon
complete -c specweave -n "__fish_seen_subcommand_from abandon" -l reason -s r -d "Reason for abandoning"
complete -c specweave -n "__fish_seen_subcommand_from abandon" -l force -s f -d "Force abandon (skip confirmation)"

# complete
complete -c specweave -n "__fish_seen_subcommand_from complete" -l silent -s s -d "Silent mode (for auto mode stop hook)"
complete -c specweave -n "__fish_seen_subcommand_from complete" -l yes -s y -d "Assume yes (silent confirmation)"
complete -c specweave -n "__fish_seen_subcommand_from complete" -l skip-validation -d "Skip quality gate validation (DANGEROUS)"
complete -c specweave -n "__fish_seen_subcommand_from complete" -l reason -s r -d "Close without a passing reports/verify.json (stored as metadata.closeReason)"
complete -c specweave -n "__fish_seen_subcommand_from complete" -l all -d "Close every active increment whose tasks are all done or skipped (requires --reason)"

# task
complete -c specweave -n "__fish_seen_subcommand_from task" -l force -s f -d "Override a live claim, unmet deps or a Files overlap"
complete -c specweave -n "__fish_seen_subcommand_from task" -l evidence -s e -d "Evidence for `done` (commit sha, test output)"
complete -c specweave -n "__fish_seen_subcommand_from task" -l run -d "Run <cmd> through the OS shell; exit 0 required, output stored as evidence"
complete -c specweave -n "__fish_seen_subcommand_from task" -l note -s n -d "Note (alias of --reason)"
complete -c specweave -n "__fish_seen_subcommand_from task" -l reason -d "Reason (required for skip / block)"
complete -c specweave -n "__fish_seen_subcommand_from task" -l all-mine -d "With `release`: release every task claimed by this agent"
complete -c specweave -n "__fish_seen_subcommand_from task" -l json -d "Machine-readable output"

# verify
complete -c specweave -n "__fish_seen_subcommand_from verify" -l cmd -d "Command to run (repeatable; overrides config/auto-detection)"
complete -c specweave -n "__fish_seen_subcommand_from verify" -l json -d "Print the verify report as JSON"

# create-increment
complete -c specweave -n "__fish_seen_subcommand_from create-increment" -l id -d "Increment ID (e.g., \"0042-my-feature\")"
complete -c specweave -n "__fish_seen_subcommand_from create-increment" -l auto-id -d "Auto-generate next available increment ID (default when --id is absent)"
complete -c specweave -n "__fish_seen_subcommand_from create-increment" -l name -d "Increment name suffix (defaults to a slug of the title)"
complete -c specweave -n "__fish_seen_subcommand_from create-increment" -l title -d "Feature title (defaults to the positional argument)"
complete -c specweave -n "__fish_seen_subcommand_from create-increment" -l description -d "Feature description (defaults to the title)"
complete -c specweave -n "__fish_seen_subcommand_from create-increment" -l project -d "Project ID (defaults to config project.name, else the folder name)"
complete -c specweave -n "__fish_seen_subcommand_from create-increment" -l board -d "Board ID for 2-level structures"
complete -c specweave -n "__fish_seen_subcommand_from create-increment" -l type -d "Increment type (feature, hotfix, bug, refactor, experiment)"
complete -c specweave -n "__fish_seen_subcommand_from create-increment" -l priority -d "Priority (P1, P2, P3)"
complete -c specweave -n "__fish_seen_subcommand_from create-increment" -l project-root -d "Override project root directory"
complete -c specweave -n "__fish_seen_subcommand_from create-increment" -l parallel -d "Opt into 3-agent fan-out planning (default: single-agent)"
complete -c specweave -n "__fish_seen_subcommand_from create-increment" -l with-plan -d "Also scaffold plan.md (optional overflow; spec.md carries the Approach)"
complete -c specweave -n "__fish_seen_subcommand_from create-increment" -l supersedes -d "Increment this one replaces (the old one is abandoned with a closeReason)"
complete -c specweave -n "__fish_seen_subcommand_from create-increment" -l parent -d "Parent increment (recorded as metadata.parent)"
complete -c specweave -n "__fish_seen_subcommand_from create-increment" -l json -d "Output result as JSON (for programmatic use)"

# handoff
complete -c specweave -n "__fish_seen_subcommand_from handoff" -l reason -d "Why you are handing off (e.g. \"out of tokens\")"
complete -c specweave -n "__fish_seen_subcommand_from handoff" -l summary -d "Short summary of where things stand"
complete -c specweave -n "__fish_seen_subcommand_from handoff" -l next -d "The exact next step for the resuming agent"
complete -c specweave -n "__fish_seen_subcommand_from handoff" -l gotcha -d "A gotcha / warning for the next agent"
complete -c specweave -n "__fish_seen_subcommand_from handoff" -l decision -d "A key decision (repeatable)"
complete -c specweave -n "__fish_seen_subcommand_from handoff" -l inline -d "Embed the full scrubbed doc body in the paste-prompt (cross-machine resume)"
complete -c specweave -n "__fish_seen_subcommand_from handoff" -l clipboard -d "Alias for --inline"
complete -c specweave -n "__fish_seen_subcommand_from handoff" -l non-specweave -d "Force the .handoff/ fallback even inside a SpecWeave workspace"
complete -c specweave -n "__fish_seen_subcommand_from handoff" -l out -d "Override the doc output path"
complete -c specweave -n "__fish_seen_subcommand_from handoff" -l json -d "Output the full result as JSON (for programmatic use)"

# next-id
complete -c specweave -n "__fish_seen_subcommand_from next-id" -l project -d "Project ID for per-project collision prevention"
complete -c specweave -n "__fish_seen_subcommand_from next-id" -l project-root -d "Override project root directory"
complete -c specweave -n "__fish_seen_subcommand_from next-id" -l name -d "Increment name to generate full ID (e.g., \"my-feature\" → \"0042-my-feature\")"

# archive
complete -c specweave -n "__fish_seen_subcommand_from archive" -l keep-last -d "Keep last N increments, archive the rest"
complete -c specweave -n "__fish_seen_subcommand_from archive" -l last -d "STRICT: Keep exactly last N increments by number, ignoring all protections"
complete -c specweave -n "__fish_seen_subcommand_from archive" -l older-than -d "Archive increments older than N days"
complete -c specweave -n "__fish_seen_subcommand_from archive" -l pattern -d "Archive increments matching pattern (regex)"
complete -c specweave -n "__fish_seen_subcommand_from archive" -l archive-completed -d "Archive all completed increments"
complete -c specweave -n "__fish_seen_subcommand_from archive" -l no-preserve-active -d "Allow archiving active/paused increments (dangerous!)"
complete -c specweave -n "__fish_seen_subcommand_from archive" -l external -d "Archive external living docs (FS-XXXE features imported from ADO/JIRA/GitHub)"
complete -c specweave -n "__fish_seen_subcommand_from archive" -l dry-run -d "Preview what would be archived without moving files"

# save
complete -c specweave -n "__fish_seen_subcommand_from save" -l interactive -s i -d "Interactive mode - ask before each step"
complete -c specweave -n "__fish_seen_subcommand_from save" -l dry-run -d "Preview without executing"
complete -c specweave -n "__fish_seen_subcommand_from save" -l sync -d "Sync strategy (rebase, merge, none)"
complete -c specweave -n "__fish_seen_subcommand_from save" -l no-stash -d "Skip auto-stash"
complete -c specweave -n "__fish_seen_subcommand_from save" -l repos -d "Only save specific repos (comma-separated)"
complete -c specweave -n "__fish_seen_subcommand_from save" -l skip-no-remote -d "Skip repos without remotes"
complete -c specweave -n "__fish_seen_subcommand_from save" -l all -d "Include all repos (even outside umbrella config)"
complete -c specweave -n "__fish_seen_subcommand_from save" -l no-push -d "Commit but don't push"
complete -c specweave -n "__fish_seen_subcommand_from save" -l force -d "Force push (requires confirmation)"
complete -c specweave -n "__fish_seen_subcommand_from save" -l branch -d "Create new branch instead of force pushing"

# status
complete -c specweave -n "__fish_seen_subcommand_from status" -l verbose -s v -d "Show detailed information"
complete -c specweave -n "__fish_seen_subcommand_from status" -l type -s t -d "Filter by increment type (feature, hotfix, bug, etc.)"

# decision-log
complete -c specweave -n "__fish_seen_subcommand_from decision-log" -l hook -d "Filter by hook name (e.g. stop-auto)"
complete -c specweave -n "__fish_seen_subcommand_from decision-log" -l decision -d "Filter by decision type (approve, block)"
complete -c specweave -n "__fish_seen_subcommand_from decision-log" -l since -d "Filter by time window (1h, 24h, 7d)"
complete -c specweave -n "__fish_seen_subcommand_from decision-log" -l limit -d "Number of entries to show (default: 20)"
complete -c specweave -n "__fish_seen_subcommand_from decision-log" -l json -d "Output raw JSON format"
complete -c specweave -n "__fish_seen_subcommand_from decision-log" -l tail -d "Follow log in real-time (like tail -f)"

# status-line
complete -c specweave -n "__fish_seen_subcommand_from status-line" -l json -d "Output JSON format"
complete -c specweave -n "__fish_seen_subcommand_from status-line" -l clear -d "Clear status line cache"
complete -c specweave -n "__fish_seen_subcommand_from status-line" -l config -d "Path to config file"

# auto
complete -c specweave -n "__fish_seen_subcommand_from auto" -l dry-run -d "Preview without activating"
complete -c specweave -n "__fish_seen_subcommand_from auto" -l all-backlog -d "Activate all backlog items"
complete -c specweave -n "__fish_seen_subcommand_from auto" -l reset -d "Clean up any stale state files"

# auto-status
complete -c specweave -n "__fish_seen_subcommand_from auto-status" -l verbose -d "Show detailed information"
complete -c specweave -n "__fish_seen_subcommand_from auto-status" -l json -d "Output as JSON"

# cancel-auto
complete -c specweave -n "__fish_seen_subcommand_from cancel-auto" -l force -d "Force cancel without confirmation"

# team
complete -c specweave -n "__fish_seen_subcommand_from team" -l mode -d "Display mode: tmux (default) or in-process"
complete -c specweave -n "__fish_seen_subcommand_from team" -l no-increment -d "Launch without requiring a SpecWeave increment (free-form agent swarm)"

# update-instructions
complete -c specweave -n "__fish_seen_subcommand_from update-instructions" -l dry-run -d "Preview changes without writing"
complete -c specweave -n "__fish_seen_subcommand_from update-instructions" -l verbose -s v -d "Show detailed merge information"

# update
complete -c specweave -n "__fish_seen_subcommand_from update" -l no-self -d "Skip CLI self-update via npm"
complete -c specweave -n "__fish_seen_subcommand_from update" -l no-plugins -d "Skip marketplace plugins refresh"
complete -c specweave -n "__fish_seen_subcommand_from update" -l all -d "Install ALL plugins (not just router)"
complete -c specweave -n "__fish_seen_subcommand_from update" -l minimal -d "Clean /plugin output (removes marketplace, no lazy loading)"
complete -c specweave -n "__fish_seen_subcommand_from update" -l check -d "Dry run - show what would change without making changes"
complete -c specweave -n "__fish_seen_subcommand_from update" -l verbose -s v -d "Show detailed output"
complete -c specweave -n "__fish_seen_subcommand_from update" -l force -s f -d "Force refresh even if up to date"

# check-discipline
complete -c specweave -n "__fish_seen_subcommand_from check-discipline" -l verbose -s v -d "Show detailed increment information"
complete -c specweave -n "__fish_seen_subcommand_from check-discipline" -l json -d "Output results as JSON"
complete -c specweave -n "__fish_seen_subcommand_from check-discipline" -l project-root -d "Project root directory"

# gc
complete -c specweave -n "__fish_seen_subcommand_from gc" -l yes -s y -d "Actually delete (default is dry-run)"
complete -c specweave -n "__fish_seen_subcommand_from gc" -l json -d "Output as JSON"
complete -c specweave -n "__fish_seen_subcommand_from gc" -l project-root -d "Project root directory"

# qa
complete -c specweave -n "__fish_seen_subcommand_from qa" -l quick -d "Quick mode (default)"
complete -c specweave -n "__fish_seen_subcommand_from qa" -l pre -d "Pre-implementation check"
complete -c specweave -n "__fish_seen_subcommand_from qa" -l gate -d "Quality gate check (comprehensive)"
complete -c specweave -n "__fish_seen_subcommand_from qa" -l full -d "Full multi-agent mode (Phase 3)"
complete -c specweave -n "__fish_seen_subcommand_from qa" -l ci -d "CI mode (exit 1 on FAIL)"
complete -c specweave -n "__fish_seen_subcommand_from qa" -l no-ai -d "Skip AI assessment (rule-based only)"
complete -c specweave -n "__fish_seen_subcommand_from qa" -l silent -d "Minimal output"
complete -c specweave -n "__fish_seen_subcommand_from qa" -l export -d "Export blockers/concerns to tasks.md"
complete -c specweave -n "__fish_seen_subcommand_from qa" -l force -s f -d "Force run even if rule-based fails"
complete -c specweave -n "__fish_seen_subcommand_from qa" -l verbose -s v -d "Show recommendations"

# link-pr
complete -c specweave -n "__fish_seen_subcommand_from link-pr" -l branch -d "Branch name"

# jobs
complete -c specweave -n "__fish_seen_subcommand_from jobs" -l all -d "Show all jobs (including completed)"
complete -c specweave -n "__fish_seen_subcommand_from jobs" -l id -d "Show details for specific job"
complete -c specweave -n "__fish_seen_subcommand_from jobs" -l logs -d "Show worker log output"
complete -c specweave -n "__fish_seen_subcommand_from jobs" -l follow -d "Follow job progress in real-time"
complete -c specweave -n "__fish_seen_subcommand_from jobs" -l kill -d "Kill running background job"
complete -c specweave -n "__fish_seen_subcommand_from jobs" -l resume -d "Resume paused job"

# living-docs
complete -c specweave -n "__fish_seen_subcommand_from living-docs" -l resume -d "Resume orphaned/paused job"
complete -c specweave -n "__fish_seen_subcommand_from living-docs" -l depth -d "Analysis depth: quick, standard, deep-native, deep-api"
complete -c specweave -n "__fish_seen_subcommand_from living-docs" -l priority -d "Priority modules (comma-separated)"
complete -c specweave -n "__fish_seen_subcommand_from living-docs" -l sources -d "Additional doc folders (comma-separated)"
complete -c specweave -n "__fish_seen_subcommand_from living-docs" -l depends-on -d "Wait for jobs before starting (comma-separated)"
complete -c specweave -n "__fish_seen_subcommand_from living-docs" -l foreground -d "Run in current session instead of background"
complete -c specweave -n "__fish_seen_subcommand_from living-docs" -l force -d "Force run even for greenfield projects"
complete -c specweave -n "__fish_seen_subcommand_from living-docs" -l full-scan -d "Force full deep scan (all phases: repos, org, arch, inconsistencies, strategy)"

# cache
complete -c specweave -n "__fish_seen_subcommand_from cache" -l rebuild -d "Rebuild cache from increments"
complete -c specweave -n "__fish_seen_subcommand_from cache" -l status -d "Show cache status (default)"
complete -c specweave -n "__fish_seen_subcommand_from cache" -l clear -d "Clear cache"
complete -c specweave -n "__fish_seen_subcommand_from cache" -l quiet -d "Minimal output"
complete -c specweave -n "__fish_seen_subcommand_from cache" -l debug -d "Show debug information"

# analytics
complete -c specweave -n "__fish_seen_subcommand_from analytics" -l export -d "Export data (json, csv)"
complete -c specweave -n "__fish_seen_subcommand_from analytics" -l since -d "Filter by time range (24h, 7d, 30d)"
complete -c specweave -n "__fish_seen_subcommand_from analytics" -l type -d "Filter by event type (command, skill, agent)"
complete -c specweave -n "__fish_seen_subcommand_from analytics" -l json -d "Output raw JSON for scripting"
complete -c specweave -n "__fish_seen_subcommand_from analytics" -l limit -d "Number of top items to show"

# analytics-push
complete -c specweave -n "__fish_seen_subcommand_from analytics-push" -l plugin -d "Source plugin name"
complete -c specweave -n "__fish_seen_subcommand_from analytics-push" -l json -d "Output as JSON"
complete -c specweave -n "__fish_seen_subcommand_from analytics-push" -l silent -d "Suppress output"

# lsp
complete -c specweave -n "__fish_seen_subcommand_from lsp" -a "refs def hover symbols search warmup status setup" -d "lsp subcommand"

# sync
complete -c specweave -n "__fish_seen_subcommand_from sync" -a "push pull status setup" -d "sync subcommand"

# docs
complete -c specweave -n "__fish_seen_subcommand_from docs" -a "preview build validate public kill status sync" -d "docs subcommand"

# refresh-plugins
complete -c specweave -n "__fish_seen_subcommand_from refresh-plugins" -l all -d "Install ALL plugins (not just core sw)"
complete -c specweave -n "__fish_seen_subcommand_from refresh-plugins" -l plugin -d "Install a specific plugin by name"
complete -c specweave -n "__fish_seen_subcommand_from refresh-plugins" -l quiet -s q -d "Suppress output (for use by hooks)"
complete -c specweave -n "__fish_seen_subcommand_from refresh-plugins" -l force -s f -d "Force reinstall (skip hash check)"
complete -c specweave -n "__fish_seen_subcommand_from refresh-plugins" -l verbose -s v -d "Show skipped plugins"

# doctor
complete -c specweave -n "__fish_seen_subcommand_from doctor" -l verbose -d "Show detailed output for each check"
complete -c specweave -n "__fish_seen_subcommand_from doctor" -l json -d "Output as JSON"
complete -c specweave -n "__fish_seen_subcommand_from doctor" -l quick -d "Skip slow checks (network, hook execution)"
complete -c specweave -n "__fish_seen_subcommand_from doctor" -l skip-external -d "Skip external tool connectivity checks"
complete -c specweave -n "__fish_seen_subcommand_from doctor" -l fix -d "Apply inline fixes (remove ghost files, stale cache, update lockfile hashes)"
complete -c specweave -n "__fish_seen_subcommand_from doctor" -l fix-status -d "Fix metadata.json <-> spec.md status desyncs (formerly sw:sync-status)"

# health
complete -c specweave -n "__fish_seen_subcommand_from health" -l json -d "Output as JSON for CI/CD pipelines"
complete -c specweave -n "__fish_seen_subcommand_from health" -l verbose -d "Show detailed output"

# session
complete -c specweave -n "__fish_seen_subcommand_from session" -a "start end" -d "session subcommand"

# detect-intent
complete -c specweave -n "__fish_seen_subcommand_from detect-intent" -l install -d "Also install detected plugins after detection"
complete -c specweave -n "__fish_seen_subcommand_from detect-intent" -l silent -d "Silent mode - no stdout output (for hooks)"
complete -c specweave -n "__fish_seen_subcommand_from detect-intent" -l file -d "Read prompt from file instead of argument (avoids shell escaping issues)"

# evaluate-completion
complete -c specweave -n "__fish_seen_subcommand_from evaluate-completion" -l model -d "Model for LLM evaluation: haiku or sonnet (default: sonnet)"
complete -c specweave -n "__fish_seen_subcommand_from evaluate-completion" -l timeout -d "Timeout in milliseconds (default: 45000)"
complete -c specweave -n "__fish_seen_subcommand_from evaluate-completion" -l silent -d "Minimal output"

# generate-rubric
complete -c specweave -n "__fish_seen_subcommand_from generate-rubric" -l refresh -d "Regenerate from current ACs, overwriting an existing non-template rubric"
complete -c specweave -n "__fish_seen_subcommand_from generate-rubric" -l silent -d "Minimal output"

# detect-project
complete -c specweave -n "__fish_seen_subcommand_from detect-project" -l name -d "Increment name for legacy name-based detection"
complete -c specweave -n "__fish_seen_subcommand_from detect-project" -l description -d "Description for legacy name-based detection"
complete -c specweave -n "__fish_seen_subcommand_from detect-project" -l install -d "Also install detected plugins after detection"
complete -c specweave -n "__fish_seen_subcommand_from detect-project" -l silent -d "Silent mode - no stdout output (for hooks)"

# export-skills
complete -c specweave -n "__fish_seen_subcommand_from export-skills" -l output -s o -d "Output directory (default: .agent-skills)"
complete -c specweave -n "__fish_seen_subcommand_from export-skills" -l plugin -s p -d "Export specific plugin only"
complete -c specweave -n "__fish_seen_subcommand_from export-skills" -l skill -s s -d "Export specific skill only"
complete -c specweave -n "__fish_seen_subcommand_from export-skills" -l dry-run -d "Preview without writing files"
complete -c specweave -n "__fish_seen_subcommand_from export-skills" -l validate -d "Validate output against Agent Skills spec"
complete -c specweave -n "__fish_seen_subcommand_from export-skills" -l verbose -s v -d "Show detailed output"

# dashboard
complete -c specweave -n "__fish_seen_subcommand_from dashboard" -l port -s p -d "Port number (default: 3456)"
complete -c specweave -n "__fish_seen_subcommand_from dashboard" -l no-browser -d "Do not open browser automatically"

# hooks
complete -c specweave -n "__fish_seen_subcommand_from hooks" -a "log" -d "hooks subcommand"

# context
complete -c specweave -n "__fish_seen_subcommand_from context" -a "projects" -d "context subcommand"

# get
complete -c specweave -n "__fish_seen_subcommand_from get" -l branch -d "Clone a specific branch"
complete -c specweave -n "__fish_seen_subcommand_from get" -l prefix -d "User story prefix (default: first 3 chars uppercase)"
complete -c specweave -n "__fish_seen_subcommand_from get" -l role -d "Repository role (frontend, backend, mobile, infra, shared)"
complete -c specweave -n "__fish_seen_subcommand_from get" -l no-init -d "Skip specweave init on cloned repo"
complete -c specweave -n "__fish_seen_subcommand_from get" -l yes -d "Skip confirmation prompts"
complete -c specweave -n "__fish_seen_subcommand_from get" -l all -d "Clone all repositories in an org (source is org name)"
complete -c specweave -n "__fish_seen_subcommand_from get" -l pattern -d "Filter repos by glob pattern, e.g. \"service-*\" (use with --all or org/* source)"
complete -c specweave -n "__fish_seen_subcommand_from get" -l limit -d "Max repos to fetch in bulk mode (default: 1000)"
complete -c specweave -n "__fish_seen_subcommand_from get" -l no-archived -d "Skip archived repositories in bulk mode"
complete -c specweave -n "__fish_seen_subcommand_from get" -l no-forks -d "Skip forked repositories in bulk mode"

# Global help option
complete -c specweave -l help -s h -d "Show help"
