artifact_location: /Users/antonabyzov/Projects/github/specweave/runs/mlflow/710263413426481409
creation_time: 1762280794233
experiment_id: '710263413426481409'
last_update_time: 1762280794233
lifecycle_stage: active
name: /Users/antonabyzov/Projects/github/specweave/.specweave/test-runs/ml-pipeline/2025-11-04T18-26-22-092Z
