site_name: SpecWeave
site_description: Spec-Driven Development Framework - Where specifications are the source of truth
site_author: SpecWeave Contributors
site_url: https://anton-abyzov.github.io/specweave

repo_name: anton-abyzov/specweave
repo_url: https://github.com/anton-abyzov/specweave
edit_uri: edit/main/.specweave/docs/public/

# PUBLIC documentation only (.specweave/docs/public/)
# Internal docs (.specweave/docs/internal/) are NOT published
docs_dir: .specweave/docs/public

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
    - toc.integrate

  icon:
    repo: fontawesome/brands/github

  logo: assets/logo.png
  favicon: assets/favicon.png

nav:
  - Overview:
    - Welcome: overview/intro.md
    - Features: overview/features.md
    - Why SpecWeave: overview/why-specweave.md
    - Getting Started: overview/quickstart.md

  - Architecture:
    - Overview: architecture/overview.md
    - System Design: architecture/system-design.md
    - Component Diagram: architecture/components.md

  - API:
    - Introduction: api/index.md
    - Authentication: api/authentication.md
    - CLI Commands: api/cli-commands.md
    - Skills API: api/skills-api.md
    - OpenAPI Specification: api/openapi.yaml

  - Guides:
    - Installation: guides/installation.md
    - Quick Start: guides/quickstart.md
    - Creating Skills: guides/creating-skills.md
    - Writing PRDs: guides/writing-prds.md
    - Feature Planning: guides/feature-planning.md
    - Testing Strategy: guides/testing-strategy.md

  - FAQ:
    - General: faq/general.md
    - Technical: faq/technical.md
    - Troubleshooting: faq/troubleshooting.md

# NOTE: Internal documentation (.specweave/docs/internal/) is NOT published
# It contains: Strategy (PRDs), Architecture (HLD/ADR/RFC), Delivery, Operations, Governance
# Access internal docs directly in the repository at .specweave/docs/internal/

plugins:
  - search:
      lang: en
  - mermaid2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - tables

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/anton-abyzov/specweave

  analytics:
    provider: google
    property: G-XXXXXXXXXX

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2025 SpecWeave Contributors
