import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  docsSidebar: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'overview/introduction',
          label: 'What is SpecWeave?',
        },
        {
          type: 'doc',
          id: 'overview/features',
          label: 'Key Features',
        },
        {
          type: 'doc',
          id: 'overview/philosophy',
          label: 'Philosophy',
        },
        {
          type: 'doc',
          id: 'metrics',
          label: '📊 DORA Metrics',
        },
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'guides/core-concepts/what-is-an-increment',
          label: 'What is an Increment?',
        },
        {
          type: 'doc',
          id: 'guides/core-concepts/living-documentation',
          label: 'Living Documentation',
        },
      ],
    },
    {
      type: 'category',
      label: 'Workflows',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'workflows/overview',
          label: '📊 Complete Journey',
        },
        {
          type: 'doc',
          id: 'workflows/planning',
          label: '📋 Planning',
        },
        {
          type: 'doc',
          id: 'workflows/implementation',
          label: '⚙️ Implementation',
        },
        {
          type: 'doc',
          id: 'workflows/brownfield',
          label: '🏢 Brownfield Projects',
        },
      ],
    },
    {
      type: 'doc',
      id: 'faq',
      label: '❓ FAQ',
    },
  ],

  // Guides sidebar
  guidesSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'guides/getting-started/quickstart',
          label: 'Quickstart',
        },
        {
          type: 'doc',
          id: 'guides/getting-started/installation',
          label: 'Installation',
        },
        {
          type: 'doc',
          id: 'faq',
          label: 'FAQ',
        },
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'guides/core-concepts/what-is-an-increment',
          label: 'What is an Increment?',
        },
        {
          type: 'doc',
          id: 'guides/core-concepts/living-documentation',
          label: 'Living Documentation',
        },
      ],
    },
    {
      type: 'category',
      label: 'Workflows',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'workflows/overview',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'workflows/planning',
          label: 'Planning',
        },
        {
          type: 'doc',
          id: 'workflows/implementation',
          label: 'Implementation',
        },
        {
          type: 'doc',
          id: 'workflows/brownfield',
          label: 'Brownfield Projects',
        },
      ],
    },
  ],

  // API sidebar
  apiSidebar: [{type: 'autogenerated', dirName: 'api'}],

  // Commands sidebar
  commandsSidebar: [
    {
      type: 'category',
      label: 'Core Commands',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'commands/status-management',
          label: 'Overview',
        },
      ],
    },
    {
      type: 'category',
      label: 'Status Management',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'commands/status',
          label: '/specweave:status',
        },
        {
          type: 'doc',
          id: 'commands/pause',
          label: '/specweave:pause',
        },
        {
          type: 'doc',
          id: 'commands/resume',
          label: '/specweave:resume',
        },
        {
          type: 'doc',
          id: 'commands/abandon',
          label: '/specweave:abandon',
        },
      ],
    },
  ],
};

export default sidebars;
