import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  docsSidebar: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'overview/introduction',
          label: 'What is SpecWeave?',
        },
        {
          type: 'doc',
          id: 'overview/features',
          label: 'Key Features',
        },
        {
          type: 'doc',
          id: 'overview/plugins-ecosystem',
          label: '🧩 Plugin Ecosystem',
        },
        {
          type: 'doc',
          id: 'overview/philosophy',
          label: 'Philosophy',
        },
        {
          type: 'doc',
          id: 'metrics',
          label: '📊 DORA Metrics',
        },
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'glossary/terms/increments',
          label: 'What is an Increment?',
        },
        {
          type: 'doc',
          id: 'glossary/terms/living-docs',
          label: 'Living Documentation',
        },
      ],
    },
    {
      type: 'category',
      label: 'Workflows',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'workflows/overview',
          label: '📊 Complete Journey',
        },
        {
          type: 'doc',
          id: 'workflows/planning',
          label: '📋 Planning',
        },
        {
          type: 'doc',
          id: 'workflows/implementation',
          label: '⚙️ Implementation',
        },
        {
          type: 'doc',
          id: 'workflows/brownfield',
          label: '🏢 Brownfield Projects',
        },
      ],
    },
    {
      type: 'doc',
      id: 'faq',
      label: '❓ FAQ',
    },
  ],

  // Integrations sidebar
  integrationsSidebar: [
    {
      type: 'category',
      label: 'Issue Trackers',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'integrations/issue-trackers',
          label: 'Overview',
        },
      ],
    },
  ],

  // Enterprise sidebar
  enterpriseSidebar: [
    {
      type: 'category',
      label: '🏢 Enterprise Migration',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'enterprise/github-migration',
          label: 'GitHub Enterprise',
        },
        {
          type: 'doc',
          id: 'enterprise/jira-migration',
          label: 'JIRA Enterprise',
        },
        {
          type: 'doc',
          id: 'enterprise/azure-devops-migration',
          label: 'Azure DevOps',
        },
      ],
    },
    {
      type: 'category',
      label: '🚀 Deployment & Release',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'enterprise/multi-environment-deployment',
          label: 'Multi-Environment Deployment',
        },
        {
          type: 'doc',
          id: 'enterprise/release-management',
          label: 'Release Management',
        },
      ],
    },
  ],

  // Guides sidebar
  guidesSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'intro',
          label: 'Quickstart',
        },
        {
          type: 'link',
          label: 'Installation',
          href: '/docs/intro#installation',
        },
        {
          type: 'doc',
          id: 'faq',
          label: 'FAQ',
        },
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'glossary/terms/increments',
          label: 'What is an Increment?',
        },
        {
          type: 'doc',
          id: 'glossary/terms/living-docs',
          label: 'Living Documentation',
        },
      ],
    },
    {
      type: 'category',
      label: 'Workflows',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'workflows/overview',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'workflows/planning',
          label: 'Planning',
        },
        {
          type: 'doc',
          id: 'workflows/implementation',
          label: 'Implementation',
        },
        {
          type: 'doc',
          id: 'workflows/brownfield',
          label: 'Brownfield Projects',
        },
      ],
    },
  ],

  // API sidebar
  apiSidebar: [{type: 'autogenerated', dirName: 'api'}],

  // Commands sidebar - Essential 8 commands only
  commandsSidebar: [
    {
      type: 'doc',
      id: 'commands/overview',
      label: '📖 Overview',
    },
    {
      type: 'category',
      label: '⚡ Essential Commands',
      collapsed: false,
      items: [
        {
          type: 'link',
          label: '1️⃣ /specweave:increment',
          href: '/docs/commands/overview#1-planning-commands',
        },
        {
          type: 'link',
          label: '2️⃣ /specweave:do',
          href: '/docs/commands/overview#2-implementation-commands',
        },
        {
          type: 'link',
          label: '3️⃣ /specweave:progress',
          href: '/docs/commands/overview#5-monitoring-commands',
        },
        {
          type: 'link',
          label: '4️⃣ /specweave:validate',
          href: '/docs/commands/overview#3-quality-assurance-commands',
        },
        {
          type: 'link',
          label: '5️⃣ /specweave:qa',
          href: '/docs/commands/overview#3-quality-assurance-commands',
        },
        {
          type: 'link',
          label: '6️⃣ /specweave:check-tests',
          href: '/docs/commands/overview#3-quality-assurance-commands',
        },
        {
          type: 'link',
          label: '7️⃣ /specweave:done',
          href: '/docs/commands/overview#4-completion-commands',
        },
        {
          type: 'link',
          label: '8️⃣ /specweave:sync-docs',
          href: '/docs/commands/overview#4-completion-commands',
        },
      ],
    },
  ],

  // Learn sidebar
  learnSidebar: [
    {
      type: 'category',
      label: '🎓 SpecWeave Academy',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'guides/lessons/index',
          label: 'Academy Overview',
        },
        {
          type: 'doc',
          id: 'guides/lessons/getting-started',
          label: 'Lesson 1: Getting Started',
        },
        {
          type: 'doc',
          id: 'guides/lessons/three-file-structure',
          label: 'Lesson 2: Three-File Structure',
        },
        {
          type: 'doc',
          id: 'guides/lessons/your-first-increment',
          label: 'Lesson 3: Your First Increment',
        },
        {
          type: 'doc',
          id: 'guides/lessons/the-next-command',
          label: 'Lesson 4: The :next Command',
        },
        {
          type: 'doc',
          id: 'guides/lessons/quality-gates',
          label: 'Lesson 5: Quality Gates',
        },
        {
          type: 'doc',
          id: 'guides/lessons/tdd-workflow',
          label: 'Lesson 6: TDD Workflow',
        },
        {
          type: 'doc',
          id: 'guides/lessons/external-tools',
          label: 'Lesson 7: External Tools',
        },
        {
          type: 'doc',
          id: 'guides/lessons/ai-model-selection',
          label: 'Lesson 8: AI Model Selection',
        },
        {
          type: 'doc',
          id: 'guides/lessons/troubleshooting',
          label: 'Lesson 9: Troubleshooting',
        },
        {
          type: 'doc',
          id: 'guides/lessons/advanced-patterns',
          label: 'Lesson 10: Advanced Patterns',
        },
      ],
    },
    {
      type: 'category',
      label: 'Foundations',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'learn/foundations/enterprise-app-development',
          label: 'Enterprise App Development',
        },
        {
          type: 'doc',
          id: 'learn/foundations/software-engineering-roles',
          label: 'Software Engineering Roles',
        },
      ],
    },
    {
      type: 'category',
      label: 'Infrastructure',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'learn/infrastructure/iac-fundamentals',
          label: 'IaC Fundamentals',
        },
      ],
    },
    {
      type: 'category',
      label: 'Backend Development',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'learn/backend/backend-fundamentals',
          label: 'Backend Fundamentals',
        },
      ],
    },
    {
      type: 'category',
      label: 'Frontend Development',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'learn/frontend/frontend-fundamentals',
          label: 'Frontend Fundamentals',
        },
      ],
    },
    {
      type: 'category',
      label: 'Testing & Quality',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'learn/testing/testing-fundamentals',
          label: 'Testing Fundamentals',
        },
      ],
    },
    {
      type: 'category',
      label: 'ML/AI',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'learn/ml-ai/ml-fundamentals',
          label: 'ML/AI Integration',
        },
      ],
    },
  ],

  // Glossary sidebar
  glossarySidebar: [
    {
      type: 'doc',
      id: 'glossary/glossary-by-category',
      label: '📖 Glossary by Category',
    },
    {
      type: 'category',
      label: 'Categories',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'glossary/categories',
        },
      ],
    },
    {
      type: 'category',
      label: 'All Terms (A-Z)',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'glossary/terms'},
      ],
    },
  ],
};

export default sidebars;
