import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  docsSidebar: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'overview/introduction',
          label: 'What is SpecWeave?',
        },
        {
          type: 'doc',
          id: 'overview/features',
          label: 'Key Features',
        },
        {
          type: 'doc',
          id: 'overview/philosophy',
          label: 'Philosophy',
        },
        {
          type: 'doc',
          id: 'metrics',
          label: '📊 DORA Metrics',
        },
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'guides/core-concepts/what-is-an-increment',
          label: 'What is an Increment?',
        },
        {
          type: 'doc',
          id: 'guides/core-concepts/living-documentation',
          label: 'Living Documentation',
        },
      ],
    },
    {
      type: 'category',
      label: 'Workflows',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'workflows/overview',
          label: '📊 Complete Journey',
        },
        {
          type: 'doc',
          id: 'workflows/planning',
          label: '📋 Planning',
        },
        {
          type: 'doc',
          id: 'workflows/implementation',
          label: '⚙️ Implementation',
        },
        {
          type: 'doc',
          id: 'workflows/brownfield',
          label: '🏢 Brownfield Projects',
        },
      ],
    },
    {
      type: 'doc',
      id: 'faq',
      label: '❓ FAQ',
    },
  ],

  // Guides sidebar
  guidesSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'guides/getting-started/quickstart',
          label: 'Quickstart',
        },
        {
          type: 'doc',
          id: 'guides/getting-started/installation',
          label: 'Installation',
        },
        {
          type: 'doc',
          id: 'faq',
          label: 'FAQ',
        },
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'guides/core-concepts/what-is-an-increment',
          label: 'What is an Increment?',
        },
        {
          type: 'doc',
          id: 'guides/core-concepts/living-documentation',
          label: 'Living Documentation',
        },
      ],
    },
    {
      type: 'category',
      label: 'Workflows',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'workflows/overview',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'workflows/planning',
          label: 'Planning',
        },
        {
          type: 'doc',
          id: 'workflows/implementation',
          label: 'Implementation',
        },
        {
          type: 'doc',
          id: 'workflows/brownfield',
          label: 'Brownfield Projects',
        },
      ],
    },
  ],

  // API sidebar
  apiSidebar: [{type: 'autogenerated', dirName: 'api'}],

  // Commands sidebar
  commandsSidebar: [
    {
      type: 'doc',
      id: 'commands/overview',
      label: '📖 Commands Overview',
    },
    {
      type: 'category',
      label: '🚀 Core Workflow',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'commands/overview',
          label: 'All Commands',
        },
      ],
    },
    {
      type: 'category',
      label: '📊 Status Management',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'commands/status-management',
          label: 'Status Commands',
        },
        {
          type: 'doc',
          id: 'commands/status',
          label: '/specweave:status',
        },
        {
          type: 'doc',
          id: 'commands/pause',
          label: '/specweave:pause',
        },
        {
          type: 'doc',
          id: 'commands/resume',
          label: '/specweave:resume',
        },
        {
          type: 'doc',
          id: 'commands/abandon',
          label: '/specweave:abandon',
        },
      ],
    },
  ],

  // Learn sidebar
  learnSidebar: [
    {
      type: 'category',
      label: 'Foundations',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'learn/foundations/enterprise-app-development',
          label: 'Enterprise App Development',
        },
        {
          type: 'doc',
          id: 'learn/foundations/software-engineering-roles',
          label: 'Software Engineering Roles',
        },
      ],
    },
    {
      type: 'category',
      label: 'Infrastructure',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'learn/infrastructure/iac-fundamentals',
          label: 'IaC Fundamentals',
        },
      ],
    },
    {
      type: 'category',
      label: 'Backend Development',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'learn/backend/backend-fundamentals',
          label: 'Backend Fundamentals',
        },
      ],
    },
    {
      type: 'category',
      label: 'Frontend Development',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'learn/frontend/frontend-fundamentals',
          label: 'Frontend Fundamentals',
        },
      ],
    },
    {
      type: 'category',
      label: 'Testing & Quality',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'learn/testing/testing-fundamentals',
          label: 'Testing Fundamentals',
        },
      ],
    },
    {
      type: 'category',
      label: 'ML/AI',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'learn/ml-ai/ml-fundamentals',
          label: 'ML/AI Integration',
        },
      ],
    },
  ],

  // Glossary sidebar
  glossarySidebar: [
    {
      type: 'doc',
      id: 'glossary/glossary',
      label: '📖 Glossary Overview',
    },
    {
      type: 'doc',
      id: 'glossary/glossary-by-category',
      label: '🗂️ Browse by Category',
    },
    {
      type: 'category',
      label: 'Categories',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'glossary/categories/architecture-category',
          label: '🏗️ Architecture & Design',
        },
        {
          type: 'doc',
          id: 'glossary/categories/infrastructure-category',
          label: '🚀 Infrastructure & Operations',
        },
        {
          type: 'doc',
          id: 'glossary/categories/backend-category',
          label: '🔌 Backend Development',
        },
        {
          type: 'doc',
          id: 'glossary/categories/frontend-category',
          label: '🎨 Frontend Development',
        },
        {
          type: 'doc',
          id: 'glossary/categories/testing-category',
          label: '✅ Testing & Quality',
        },
        {
          type: 'doc',
          id: 'glossary/categories/devops-category',
          label: '🛠️ DevOps & Tools',
        },
        {
          type: 'doc',
          id: 'glossary/categories/collaboration-category',
          label: '👥 Collaboration & Management',
        },
        {
          type: 'doc',
          id: 'glossary/categories/performance-category',
          label: '⚡ Performance & Scalability',
        },
        {
          type: 'doc',
          id: 'glossary/categories/ml-ai-category',
          label: '🤖 ML/AI',
        },
      ],
    },
    {
      type: 'category',
      label: 'All Terms (A-Z)',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'glossary/terms'},
      ],
    },
  ],
};

export default sidebars;
