/**
 * Market Research Report Generator
 *
 * Generates markdown reports summarizing vision analysis results.
 */

import fs from 'fs/promises';
import path from 'path';
import type { VisionInsights } from './types.js';

/**
 * ReportGenerator - Generates market research reports
 *
 * **Usage**:
 * ```typescript
 * await ReportGenerator.generate(insights);
 * // Creates .specweave/reports/market-research.md
 * ```
 */
export class ReportGenerator {
  /**
   * Default report path
   */
  private static readonly REPORT_PATH = '.specweave/reports/market-research.md';

  /**
   * Generate market research report
   *
   * @param insights - Vision insights to include in report
   * @param reportPath - Optional custom report path
   */
  static async generate(
    insights: VisionInsights,
    reportPath: string = ReportGenerator.REPORT_PATH
  ): Promise<void> {
    const markdown = ReportGenerator.createMarkdown(insights);

    // Ensure reports directory exists
    const dir = path.dirname(reportPath);
    await fs.mkdir(dir, { recursive: true });

    // Write report
    await fs.writeFile(reportPath, markdown, 'utf-8');
  }

  /**
   * Create markdown content from insights
   *
   * @param insights - Vision insights
   * @returns Markdown string
   */
  private static createMarkdown(insights: VisionInsights): string {
    const timestamp = new Date().toISOString();
    const date = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    const sections: string[] = [];

    // Header
    sections.push('# Market Research Report');
    sections.push('');
    sections.push(`**Generated**: ${date}`);
    sections.push(`**Timestamp**: ${timestamp}`);
    sections.push('');
    sections.push('---');
    sections.push('');

    // Vision
    sections.push('## Product Vision');
    sections.push('');
    sections.push(insights.rawVision);
    sections.push('');

    // Keywords
    sections.push('## Keywords & Domain Focus');
    sections.push('');
    sections.push('**Extracted Keywords**:');
    sections.push('');
    insights.keywords.forEach(keyword => {
      sections.push(`- ${keyword}`);
    });
    sections.push('');

    // Market Category
    sections.push('## Market Classification');
    sections.push('');
    sections.push(`**Category**: ${insights.market}`);
    sections.push(`**Confidence**: ${(insights.confidence * 100).toFixed(0)}%`);
    sections.push('');

    // Opportunity Score
    sections.push('## Opportunity Analysis');
    sections.push('');
    sections.push(`**Opportunity Score**: ${insights.opportunityScore}/10`);
    sections.push(`**Viral Potential**: ${insights.viralPotential ? 'Yes' : 'No'}`);
    sections.push('');

    // Competitors
    if (insights.competitors.length > 0) {
      sections.push('## Competitive Landscape');
      sections.push('');
      sections.push('**Similar Products**:');
      sections.push('');

      sections.push('| Product | URL | Similarity | Strengths | Weaknesses |');
      sections.push('|---------|-----|------------|-----------|------------|');

      insights.competitors.forEach(comp => {
        const similarity = 'N/A'; // Similarity scoring not yet implemented
        const strengths = comp.strengths.join(', ') || 'N/A';
        const weaknesses = comp.weaknesses.join(', ') || 'N/A';
        sections.push(`| ${comp.name} | ${comp.url || 'N/A'} | ${similarity} | ${strengths} | ${weaknesses} |`);
      });

      sections.push('');
    } else {
      sections.push('## Competitive Landscape');
      sections.push('');
      sections.push('No similar products identified.');
      sections.push('');
    }

    // Follow-up Questions
    if (insights.followUpQuestions.length > 0) {
      sections.push('## Recommended Next Steps');
      sections.push('');
      sections.push('To refine your product strategy, consider these questions:');
      sections.push('');

      insights.followUpQuestions.forEach((q, idx) => {
        sections.push(`${idx + 1}. **${q.question}**`);
        sections.push('');
      });
    }

    // Footer
    sections.push('---');
    sections.push('');
    sections.push('*This report was generated by SpecWeave Strategic Init*');
    sections.push('');

    return sections.join('\n');
  }
}
