/**
 * Docusaurus configuration generator
 * Generates docusaurus.config.js with sensible defaults
 */

import * as path from 'path';
import * as fs from 'fs-extra';
import { DocusaurusConfig } from './types';

/**
 * Generate docusaurus.config.js content
 */
export function generateDocusaurusConfig(config: DocusaurusConfig): string {
  const { title, tagline, url, baseUrl, docsPath, theme = 'default' } = config;

  return `// @ts-check
// This is a Docusaurus site configuration object.
// Auto-generated by SpecWeave docs-preview plugin
// Generated: ${new Date().toISOString()}

import {themes as prismThemes} from 'prism-react-renderer';

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: '${title}',
  tagline: '${tagline}',
  favicon: 'img/favicon.ico',

  // Production URL
  url: '${url}',
  baseUrl: '${baseUrl}',

  // GitHub Pages deployment config
  organizationName: 'your-org',
  projectName: 'your-repo',

  onBrokenLinks: 'warn',
  onBrokenMarkdownLinks: 'warn',
  onBrokenAnchors: 'warn',

  // Internationalization
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          routeBasePath: '/',
          path: '${docsPath}',
          sidebarPath: './sidebars.js',
          editUrl: undefined, // Disable "Edit this page" for internal docs
          remarkPlugins: [],
          rehypePlugins: [],
          beforeDefaultRemarkPlugins: [],
          beforeDefaultRehypePlugins: [],
        },
        blog: false, // Disable blog
        theme: {
          customCss: './src/css/custom.css',
        },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      // Social card image (optional)
      image: 'img/docusaurus-social-card.jpg',

      navbar: {
        title: '${title}',
        logo: {
          alt: '${title} Logo',
          src: 'img/logo.svg',
        },
        items: [
          {
            type: 'docSidebar',
            sidebarId: 'docs',
            position: 'left',
            label: 'Documentation',
          },
        ],
      },

      footer: {
        style: 'dark',
        links: [
          {
            title: 'Documentation',
            items: [
              {
                label: 'Strategy',
                to: '/strategy',
              },
              {
                label: 'Architecture',
                to: '/architecture',
              },
            ],
          },
        ],
        copyright: \`Copyright © \${new Date().getFullYear()} SpecWeave. Built with Docusaurus.\`,
      },

      prism: {
        theme: prismThemes.github,
        darkTheme: prismThemes.dracula,
        additionalLanguages: ['bash', 'typescript', 'javascript', 'json', 'yaml'],
      },
    }),

  // Mermaid diagrams support
  markdown: {
    mermaid: true,
    format: 'mdx',
    mdx1Compat: {
      comments: true,
      admonitions: true,
      headingIds: true,
    },
  },
  themes: ['@docusaurus/theme-mermaid'],
};

export default config;
`;
}

/**
 * Write docusaurus.config.js to file
 */
export async function writeDocusaurusConfig(targetDir: string, config: DocusaurusConfig): Promise<void> {
  const configPath = path.join(targetDir, 'docusaurus.config.js');
  const content = generateDocusaurusConfig(config);
  await fs.ensureDir(targetDir);
  await fs.writeFile(configPath, content, 'utf-8');
}

/**
 * Generate package.json for Docusaurus site
 */
export function generatePackageJSON(title: string): string {
  return JSON.stringify(
    {
      name: 'specweave-docs',
      version: '1.0.0',
      description: `${title} - Documentation Site`,
      private: true,
      scripts: {
        docusaurus: 'docusaurus',
        start: 'docusaurus start',
        build: 'docusaurus build',
        swizzle: 'docusaurus swizzle',
        deploy: 'docusaurus deploy',
        clear: 'docusaurus clear',
        serve: 'docusaurus serve',
        'write-translations': 'docusaurus write-translations',
        'write-heading-ids': 'docusaurus write-heading-ids'
      },
      dependencies: {
        '@docusaurus/core': '^3.0.0',
        '@docusaurus/preset-classic': '^3.0.0',
        '@docusaurus/theme-mermaid': '^3.0.0',
        '@mdx-js/react': '^3.0.0',
        clsx: '^2.0.0',
        'prism-react-renderer': '^2.1.0',
        react: '^18.0.0',
        'react-dom': '^18.0.0'
      },
      devDependencies: {
        '@docusaurus/module-type-aliases': '^3.0.0',
        '@docusaurus/types': '^3.0.0'
      },
      engines: {
        node: '>=18.0'
      }
    },
    null,
    2
  );
}

/**
 * Write package.json to file
 */
export async function writePackageJSON(targetDir: string, title: string): Promise<void> {
  const packagePath = path.join(targetDir, 'package.json');
  const content = generatePackageJSON(title);
  await fs.ensureDir(targetDir);
  await fs.writeFile(packagePath, content, 'utf-8');
}

/**
 * Generate custom CSS for theme customization
 */
export function generateCustomCSS(theme: string): string {
  const themes: Record<string, string> = {
    default: `
:root {
  --ifm-color-primary: #2e8555;
  --ifm-color-primary-dark: #29784c;
  --ifm-color-primary-darker: #277148;
  --ifm-color-primary-darkest: #205d3b;
  --ifm-color-primary-light: #33925d;
  --ifm-color-primary-lighter: #359962;
  --ifm-color-primary-lightest: #3cad6e;
  --ifm-code-font-size: 95%;
  --docusaurus-highlighted-code-line-bg: rgba(0, 0, 0, 0.1);
}

[data-theme='dark'] {
  --ifm-color-primary: #25c2a0;
  --ifm-color-primary-dark: #21af90;
  --ifm-color-primary-darker: #1fa588;
  --ifm-color-primary-darkest: #1a8870;
  --ifm-color-primary-light: #29d5b0;
  --ifm-color-primary-lighter: #32d8b4;
  --ifm-color-primary-lightest: #4fddbf;
  --docusaurus-highlighted-code-line-bg: rgba(0, 0, 0, 0.3);
}
`,
    classic: `
:root {
  --ifm-color-primary: #0066cc;
  --ifm-color-primary-dark: #005cb8;
  --ifm-color-primary-darker: #0056ad;
  --ifm-color-primary-darkest: #00478f;
  --ifm-color-primary-light: #0070e0;
  --ifm-color-primary-lighter: #0076eb;
  --ifm-color-primary-lightest: #1a85ff;
  --ifm-code-font-size: 95%;
}
`,
    dark: `
:root {
  --ifm-color-primary: #1e1e1e;
  --ifm-background-color: #0d1117;
  --ifm-code-font-size: 95%;
}

[data-theme='dark'] {
  --ifm-color-primary: #58a6ff;
  --ifm-background-color: #0d1117;
}
`
  };

  return `/**
 * Custom CSS for SpecWeave documentation
 * Theme: ${theme}
 * Auto-generated by SpecWeave docs-preview plugin
 */

${themes[theme]}

/* Custom styles */
.markdown {
  --ifm-h1-font-size: 2rem;
  --ifm-h2-font-size: 1.5rem;
  --ifm-h3-font-size: 1.25rem;
}

/* Code blocks */
.prism-code {
  font-size: 0.9rem;
}

/* Mermaid diagrams */
.docusaurus-mermaid-container {
  text-align: center;
  margin: 2rem 0;
}
`;
}

/**
 * Write custom CSS to file
 */
export async function writeCustomCSS(targetDir: string, theme: string): Promise<void> {
  const cssPath = path.join(targetDir, 'src', 'css', 'custom.css');
  const content = generateCustomCSS(theme);
  await fs.ensureDir(path.dirname(cssPath));
  await fs.writeFile(cssPath, content, 'utf-8');
}

/**
 * Generate index page (landing page)
 */
export function generateIndexPage(title: string, tagline: string): string {
  return `import React from 'react';
import clsx from 'clsx';
import Link from '@docusaurus/Link';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import Layout from '@theme/Layout';
import styles from './index.module.css';

function HomepageHeader() {
  const {siteConfig} = useDocusaurusContext();
  return (
    <header className={clsx('hero hero--primary', styles.heroBanner)}>
      <div className="container">
        <h1 className="hero__title">{siteConfig.title}</h1>
        <p className="hero__subtitle">{siteConfig.tagline}</p>
        <div className={styles.buttons}>
          <Link
            className="button button--secondary button--lg"
            to="/strategy">
            View Documentation
          </Link>
        </div>
      </div>
    </header>
  );
}

export default function Home() {
  const {siteConfig} = useDocusaurusContext();
  return (
    <Layout
      title={\`\${siteConfig.title}\`}
      description="${tagline}">
      <HomepageHeader />
      <main>
        <div className="container" style={{marginTop: '2rem', marginBottom: '2rem'}}>
          <div className="row">
            <div className="col col--12">
              <h2>Welcome to ${title}</h2>
              <p>
                This is your SpecWeave documentation site, automatically generated from your
                <code>.specweave/docs/</code> folder.
              </p>
              <p>
                Use the sidebar to navigate through your documentation:
              </p>
              <ul>
                <li><strong>Strategy</strong>: Business rationale, PRDs, OKRs</li>
                <li><strong>Specs</strong>: Feature specifications and user stories</li>
                <li><strong>Architecture</strong>: Technical design, ADRs, diagrams</li>
                <li><strong>Delivery</strong>: Build & release processes</li>
                <li><strong>Operations</strong>: Runbooks, SLOs, incidents</li>
                <li><strong>Governance</strong>: Policies, security, compliance</li>
              </ul>
            </div>
          </div>
        </div>
      </main>
    </Layout>
  );
}
`;
}

/**
 * Write index page to file
 */
export async function writeIndexPage(targetDir: string, title: string, tagline: string): Promise<void> {
  const indexPath = path.join(targetDir, 'src', 'pages', 'index.js');
  const content = generateIndexPage(title, tagline);
  await fs.ensureDir(path.dirname(indexPath));
  await fs.writeFile(indexPath, content, 'utf-8');
}

/**
 * Generate index.module.css for landing page styles
 */
export function generateIndexModuleCSS(): string {
  return `.heroBanner {
  padding: 4rem 0;
  text-align: center;
  position: relative;
  overflow: hidden;
}

@media screen and (max-width: 996px) {
  .heroBanner {
    padding: 2rem;
  }
}

.buttons {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 1rem;
  margin-top: 2rem;
}
`;
}

/**
 * Write index.module.css to file
 */
export async function writeIndexModuleCSS(targetDir: string): Promise<void> {
  const cssPath = path.join(targetDir, 'src', 'pages', 'index.module.css');
  const content = generateIndexModuleCSS();
  await fs.ensureDir(path.dirname(cssPath));
  await fs.writeFile(cssPath, content, 'utf-8');
}
