/**
 * Main orchestrator for Docusaurus setup
 * Coordinates all setup steps: install, config, sidebar, server launch
 */

import * as path from 'path';
import * as fs from '../../utils/fs-native.js';
import { checkNodeVersion, installDocusaurus, isDocusaurusInstalled } from './package-installer.js';
import { buildSidebar, countDocuments, countCategories } from './sidebar-builder.js';
import {
  writeDocusaurusConfig, writePackageJSON, writeCustomCSS,
  writeIndexPage, writeIndexModuleCSS,
  generateLogoSVG, generateFaviconSVG
} from './config-generator.js';
import { startDevServer, findAvailablePort } from './server-manager.js';
import { detectProjectMetadata } from './project-detector.js';
import { SetupOptions, DocusaurusConfig, ServerProcess } from './types.js';

/** Default port range — avoids 3000 which is commonly used by dev servers */
const DEFAULT_PORT_START = 3016;
const DEFAULT_PORT_END = 3030;

/** Primary theme color used for logo/favicon generation */
const PRIMARY_COLOR = '#4f46e5';

/**
 * Full Docusaurus setup workflow
 */
export async function setupDocusaurus(options: SetupOptions): Promise<void> {
  const { projectRoot, targetDir, docsPath, config, force = false } = options;

  console.log('\u{1F4E6} Setting up documentation preview...\n');

  // Step 1: Check Node.js version
  console.log('1. Checking Node.js version...');
  const nodeVersion = await checkNodeVersion();
  if (!nodeVersion.compatible) {
    throw new Error(
      `Node.js 18+ required (found: ${nodeVersion.version})\n` +
        'Install Node.js from: https://nodejs.org/'
    );
  }
  console.log(`   \u2705 Node.js ${nodeVersion.version}\n`);

  // Step 2: Check if packages already installed (skip npm install if so)
  const packagesInstalled = await isDocusaurusInstalled(targetDir);

  if (!force && packagesInstalled) {
    console.log('\u2705 Packages already installed\n');
  } else {
    // Step 3: Create target directory
    console.log('2. Creating docs-site directory...');
    await fs.ensureDir(targetDir);
    console.log('   \u2705 Directory created\n');

    // Step 4: Generate package.json
    console.log('3. Generating package.json...');
    await writePackageJSON(targetDir, config.title);
    console.log('   \u2705 package.json created\n');

    // Step 5: Install Docusaurus packages
    console.log('4. Installing packages (this may take 30-60 seconds)...');
    await installDocusaurus(targetDir);
    console.log('   \u2705 Installation complete\n');
  }

  // Always regenerate config files (picks up project metadata changes)
  console.log('5. Generating docusaurus.config.js...');
  await writeDocusaurusConfig(targetDir, config);
  console.log('   \u2705 Configuration generated\n');

  // Step 7: Count docs for info display
  console.log('6. Scanning documentation folders...');
  const sidebar = await buildSidebar({
    docsPath,
    excludeFolders: config.excludeFolders || ['legacy', 'node_modules', '_archive'],
    maxDepth: 5
  });

  const docCount = countDocuments(sidebar);
  const catCount = countCategories(sidebar);
  console.log(`   \u2705 Found ${docCount} documents in ${catCount} categories\n`);

  // Step 8: Write autogenerated sidebar
  console.log('7. Generating sidebars.js...');
  const sidebarPath = path.join(targetDir, 'sidebars.js');
  const autogeneratedSidebar = `/**
 * Auto-generated sidebar for documentation
 * Generated: ${new Date().toISOString()}
 * Uses Docusaurus autogenerated sidebar for reliability with large doc sets
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

module.exports = sidebars;
`;
  await fs.writeFile(sidebarPath, autogeneratedSidebar, 'utf-8');
  console.log('   \u2705 Sidebar generated\n');

  // Step 9: Create landing page
  console.log('8. Creating landing page...');
  const categories = config.projectMetadata?.categories || [];
  await writeIndexPage(targetDir, config.title, config.tagline, categories);
  await writeIndexModuleCSS(targetDir);
  console.log('   \u2705 Landing page created\n');

  // Step 10: Create custom CSS
  console.log('9. Creating custom theme...');
  await writeCustomCSS(targetDir, config.theme || 'default');
  console.log('   \u2705 Theme configured\n');

  // Step 11: Generate static assets (logo + favicon)
  console.log('10. Generating project assets...');
  const staticImgDir = path.join(targetDir, 'static', 'img');
  await fs.ensureDir(staticImgDir);

  const metadata = config.projectMetadata;
  if (metadata) {
    const logoSvg = generateLogoSVG(metadata.initials, PRIMARY_COLOR);
    await fs.writeFile(path.join(staticImgDir, 'logo.svg'), logoSvg, 'utf-8');

    const faviconSvg = generateFaviconSVG(metadata.initials, PRIMARY_COLOR);
    await fs.writeFile(path.join(staticImgDir, 'favicon.svg'), faviconSvg, 'utf-8');
  }
  console.log('   \u2705 Assets generated\n');

  console.log('\u2705 Setup complete!\n');
}

/**
 * Quick setup with defaults — detects project metadata automatically
 */
export async function quickSetup(projectRoot: string): Promise<void> {
  const targetDir = path.join(projectRoot, '.specweave', 'docs-site-internal');
  const docsPath = path.join(projectRoot, '.specweave', 'docs', 'internal');

  // Check if docs exist
  if (!await fs.pathExists(docsPath)) {
    throw new Error(
      'No documentation found.\n' +
        'Create documentation by completing your first increment:\n' +
        '  /sw:increment "your feature"'
    );
  }

  // Detect project metadata
  const metadata = await detectProjectMetadata(projectRoot, docsPath);

  const config: DocusaurusConfig = {
    title: `${metadata.name} Documentation`,
    tagline: metadata.description,
    url: 'http://localhost',
    baseUrl: '/',
    docsPath: '../docs/internal',
    port: DEFAULT_PORT_START,
    theme: 'default',
    excludeFolders: ['legacy', 'node_modules'],
    projectMetadata: metadata
  };

  await setupDocusaurus({
    projectRoot,
    targetDir,
    docsPath,
    config
  });
}

/**
 * Launch preview (setup if needed, then start server)
 */
export async function launchPreview(
  projectRoot: string,
  options: { port?: number; openBrowser?: boolean; force?: boolean } = {}
): Promise<ServerProcess> {
  const targetDir = path.join(projectRoot, '.specweave', 'docs-site-internal');

  // Always run quickSetup to regenerate configs with fresh metadata
  // (packages are only installed once unless --force)
  await quickSetup(projectRoot);

  // Force reinstall packages if explicitly requested
  if (options.force) {
    const docsPath = path.join(projectRoot, '.specweave', 'docs', 'internal');
    const metadata = await detectProjectMetadata(projectRoot, docsPath);
    const config: DocusaurusConfig = {
      title: `${metadata.name} Documentation`,
      tagline: metadata.description,
      url: 'http://localhost',
      baseUrl: '/',
      docsPath: '../docs/internal',
      port: DEFAULT_PORT_START,
      theme: 'default',
      excludeFolders: ['legacy', 'node_modules'],
      projectMetadata: metadata
    };
    await setupDocusaurus({
      projectRoot,
      targetDir,
      docsPath: path.join(projectRoot, '.specweave', 'docs', 'internal'),
      config,
      force: true
    });
  }

  // Find available port (avoids 3000)
  const port = options.port || await findAvailablePort(DEFAULT_PORT_START, DEFAULT_PORT_END);
  console.log(`Starting server on port ${port}...`);

  // Start dev server
  const server = await startDevServer(targetDir, {
    port,
    openBrowser: options.openBrowser !== false
  });

  console.log(`\n\u{1F310} Documentation available at: ${server.url}`);
  console.log('\u{1F504} Hot reload enabled - edit docs and see changes instantly');
  console.log('\u{1F4A1} Press Ctrl+C to stop the server\n');

  return server;
}

/**
 * Build static site
 */
export async function buildStaticSite(projectRoot: string): Promise<void> {
  const targetDir = path.join(projectRoot, '.specweave', 'docs-site-internal');

  // Check if installed
  if (!await isDocusaurusInstalled(targetDir)) {
    throw new Error(
      'Docusaurus not installed.\n' +
        'Run: /sw:docs preview (this will install it)'
    );
  }

  console.log('\u{1F4E6} Building static documentation site...\n');

  const { spawn } = await import('child_process');

  return new Promise((resolve, reject) => {
    const buildProcess = spawn('npm', ['run', 'build'], {
      cwd: targetDir,
      stdio: 'inherit',
      shell: true
    });

    buildProcess.on('close', (code) => {
      if (code === 0) {
        const buildPath = path.join(targetDir, 'build');
        console.log('\n\u2705 Build complete!');
        console.log(`\u{1F4C1} Output: ${buildPath}\n`);
        resolve();
      } else {
        reject(new Error(`Build failed with code ${code}`));
      }
    });

    buildProcess.on('error', (error) => {
      reject(new Error(`Failed to start build: ${error.message}`));
    });
  });
}

/**
 * Check if setup is needed
 */
export async function isSetupNeeded(projectRoot: string): Promise<boolean> {
  const targetDir = path.join(projectRoot, '.specweave', 'docs-site-internal');
  return !(await isDocusaurusInstalled(targetDir));
}

/**
 * Get docs site path
 */
export function getDocsSitePath(projectRoot: string): string {
  return path.join(projectRoot, '.specweave', 'docs-site-internal');
}

/**
 * Get docs path
 */
export function getDocsPath(projectRoot: string): string {
  return path.join(projectRoot, '.specweave', 'docs', 'internal');
}
