/**
 * Instruction File Merger (2.0) - CLAUDE.md / AGENTS.md
 *
 * parse → classify → render.
 *
 * File layout produced:
 *   [user content that was above the META line]
 *   <!-- SW:META template=".." version=".." sections=".." -->
 *   <!-- SW:SECTION:id version=".." --> … <!-- SW:END:id -->   (template order)
 *   [user-owned tail: ## Commands / ## Project notes]        (added once)
 *   [all other user content, in original order]
 *
 * Guarantees:
 * - user content (anything outside SW markers) is never dropped
 * - sections removed from the template are deleted, ids reported
 * - a section's version attr changes only when its body changed
 * - idempotent: a second run over the output is byte-identical
 * - broken markers are repaired (body kept as user content), never abort
 * - legacy 1.x files (no markers, or "↓ ORIGINAL ↓" stacks) are stripped of
 *   known 1.x template blocks by heading and de-duplicated
 */

import * as fs from '../../../utils/fs-native.js';
import * as path from 'path';
import { createRequire } from 'module';
import { fileURLToPath } from 'url';
import type { StackCommands } from './stack-detector.js';

export type TemplateType = 'claude' | 'agents';

/** Major version of the managed-block schema. Files below it are migrated. */
export const TEMPLATE_SCHEMA_MAJOR = 2;

export interface TemplateSection {
  id: string;
  order: number;
  required: boolean;
  content: string;
}

export interface ParsedTemplate {
  sections: TemplateSection[];
  /** Content after the last `<!-- /SECTION -->`: user-owned, emitted once. */
  tail: string;
}

export interface MergeOptions {
  /** Template tail (user-owned). Ignored when a ParsedTemplate is passed. */
  tail?: string;
  /** Detected project commands for the {{BUILD_CMD}} family of placeholders. */
  commands?: StackCommands;
}

export interface MigrationInfo {
  fromVersion: string;
  removed: string[];
}

export interface MergeResult {
  content: string;
  action: 'created' | 'merged' | 'unchanged';
  updated: string[];
  added: string[];
  removed: string[];
  preserved: number;
  warnings: string[];
  migration: MigrationInfo | null;
}

// ---------------------------------------------------------------------------
// Marker grammar
// ---------------------------------------------------------------------------

const META_RE = /<!-- SW:META\b([^>]*)-->/;
const START_RE = /^\s*<!-- SW:SECTION:([\w-]+)(?:\s+version="([^"]*)")?\s*-->\s*$/;
const END_RE = /^\s*<!-- SW:END:([\w-]+)\s*-->\s*$/;
const LEGACY_MARKER_RE = /^\s*<!--\s*↓\s*(?:ORIGINAL|PROJECT-SPECIFIC)[^>]*-->\s*$/;
const TEMPLATE_START_RE = /^\s*<!-- SECTION:([\w-]+)(?:\s+(required))?\s*-->\s*$/;
const TEMPLATE_END_RE = /^\s*<!-- \/SECTION -->\s*$/;
const HR_RE = /^\s*---\s*$/;
const H2_RE = /^## /;
const H1_RE = /^# /;
const FENCE_RE = /^\s*(```|~~~)/;

/** Lines that were part of 1.x templates but carry no heading. */
const LEGACY_LINE_RES: RegExp[] = [
  /^# .+ - SpecWeave Reference\s*$/,
  /^\*\*Framework\*\*: SpecWeave\b/,
  /^<!-- API: Enable `apiDocs`/,
  /^\*\*Generated by SpecWeave\*\*/,
  /^\*\*Compatible with\*\*: Claude Code/,
  /^\*\*Last Updated\*\*: \{TIMESTAMP\}/,
  /^<!-- Auto-generated by SpecWeave/,
];

/**
 * Known 1.x template H2 headings per template type. A block is stripped when
 * its heading matches AND (no signatures are listed OR the body contains one
 * of them). Signatures protect user-written sections that reuse a generic
 * heading such as "## Rules" or "## Structure".
 */
const LEGACY_HEADINGS: Record<TemplateType, Record<string, string[]>> = {
  claude: {
    'Hook Instructions Override Everything': [],
    'Skills & Plugins': ['Skill chaining', 'Complexity gate', 'Skill({ skill:'],
    'LSP (Code Intelligence)': [],
    'Getting Started': ['Your first increment starts at'],
    'Auto-Detection': ['auto-route', 'Opt-out phrases'],
    'Workflow Orchestration': ['Plan Mode Default', 'Subagent Strategy', 'Verification Before Done', 'Think-Before-Act'],
    'Rules': ['.specweave/increments/####-name/', 'Unique IDs', 'emergency mode', 'Initialization guard'],
    'Workflow': ['| Cmd | Action |', 'Ship while sleeping'],
    'Nested Repos': ['for d in repositories', 'Before git operations'],
    'Context': ['Check ADRs at', '/sw:docs <topic>'],
    'Structure': ['Increment root', 'Everything else → subfolders'],
    'Task Format': ['Satisfies ACs', '**User Story**: US-001'],
    'Secrets': ['grep -q'],
    'External Sync': ['Feature→Milestone', 'progress-sync'],
    'Testing Pipeline (MANDATORY)': [],
    'TDD': ['defaultTestMode', 'RED→GREEN→REFACTOR'],
    'Limits': ['Max 1500 lines/file'],
    'Troubleshooting': ['Skills missing', 'refresh-plugins', 'Restart Claude Code'],
    'Plugin Auto-Loading': [],
    'Principles': ['Spec-first', 'No Laziness'],
    'Bidirectional Linking': [],
    'External Services': ['CLI tools first'],
    'Auto Mode': ['/sw:auto', 'IMPLEMENT → TEST'],
    'Docs': ['verified-skill.com', 'spec-weave.com'],
    'Using SpecWeave with Other AI Tools': [],
    // older 1.x headings (unambiguous)
    'Meta-Rule: Think-Before-Act': [],
    'Lazy Plugin Loading': [],
    'SpecWeave Auto-Routing (CRITICAL)': [],
    'Self-Improving Skills (Reflect)': [],
    'Non-Claude AI Tools': [],
    'Secrets Check': ['grep -q'],
    'Quick Commands': ['sw:increment'],
    'Living Docs Context': [],
    'Claude Code Concepts (2.1.3+)': [],
    'Auto-Execute Rule (CRITICAL)': [],
  },
  agents: {
    'Essential Rules': ['NEVER pollute project root', 'ONLY 4 files in increment root'],
    'Workflow Orchestration': [
      'Plan Before Code',
      'Verify Before Done',
      'Dependencies First',
      'Claude Code has built-in orchestration',
      'EnterPlanMode',
    ],
    'Core Principles (Quality)': [],
    'Commands Reference': ['sw:increment', '| Tool | Invocation |'],
    'Non-Claude Tools (Cursor, Copilot, etc.)': [],
    'Sync Workflow': ['sw:progress-sync', 'Source of Truth'],
    'Context Loading': ['Token-Efficient', 'Read only what'],
    'Project Structure': ['Every workspace uses `repositories/`', 'Feature increments (0001-9999)', 'Living docs (extracted user stories)'],
    'Agents (Roles)': ['{AGENTS_SECTION}', 'Adopt role perspective'],
    'Skills (Capabilities)': ['{SKILLS_SECTION}', 'Skills auto-activate', '.cursor/skills/'],
    'Task Format': ['Satisfies ACs', '**User Story**: US-001', 'Test Plan'],
    'User Story Format (CRITICAL for spec.md)': [],
    'Workflows': ['specweave context projects', 'sw:grill', 'Creating Increment'],
    'Troubleshooting': ['non-Claude', 'sw:progress-sync', 'Missing **Project**'],
    'Documentation': ['| Resource | Purpose |', 'verified-skill.com'],
    // older 1.x headings (unambiguous)
    '🚨 CRITICAL: How to Use This File (Non-Claude Code Tools)': [],
    '📑 SECTION INDEX (Your Navigation Menu)': [],
    'Section Index (Use Ctrl+F to Navigate)': [],
    '🎯 CRITICAL: Skills Are Your Expert Manuals (Read First!)': [],
    '🚀 SpecWeave Commands (Executable Workflows)': [],
    '🔌 Plugin Architecture (IMPORTANT FOR NON-CLAUDE TOOLS)': [],
    '🔗 External Tracker Sync (CRITICAL FOR NON-CLAUDE TOOLS)': [],
    '📝 Documentation Updates (CRITICAL FOR NON-CLAUDE TOOLS)': [],
    'Available Agents (Specialized Roles)': [],
    'Available Skills (Specialized Capabilities)': [],
    'Finding the Right Agent or Skill': [],
    'Quick Start': ['specweave context projects', '/sw:increment', 'Create Your First Increment'],
    'Plugin Commands': ['| Command | Plugin |', 'sw-github:sync'],
  },
};

/** "## Skill Memories": template boilerplate is dropped, user bullets are kept. */
const SKILL_MEMORIES_HEADING = 'Skill Memories';
const SKILL_MEMORIES_BOILERPLATE: RegExp[] = [
  /^SpecWeave learns from corrections\./,
  /^\*\*Disable\*\*: Set `"reflect"/,
];

// ---------------------------------------------------------------------------
// Template parsing
// ---------------------------------------------------------------------------

export function parseTemplate(content: string): ParsedTemplate {
  const lines = content.replace(/\r\n/g, '\n').split('\n');
  const sections: TemplateSection[] = [];
  let cur: { id: string; req: boolean; lines: string[] } | null = null;
  let lastEnd = -1;

  const flush = (): void => {
    if (!cur) return;
    sections.push({
      id: cur.id,
      order: sections.length,
      required: cur.req,
      content: cur.lines.join('\n').trim(),
    });
    cur = null;
  };

  lines.forEach((l, i) => {
    const start = l.match(TEMPLATE_START_RE);
    if (start) {
      flush();
      cur = { id: start[1], req: start[2] === 'required', lines: [] };
      return;
    }
    if (TEMPLATE_END_RE.test(l)) {
      flush();
      lastEnd = i;
      return;
    }
    if (cur) cur.lines.push(l);
  });
  flush();

  const tail = lastEnd >= 0 && sections.length > 0 ? lines.slice(lastEnd + 1).join('\n').trim() : '';
  return { sections, tail };
}

export function parseTemplateSections(content: string): TemplateSection[] {
  return parseTemplate(content).sections;
}

// ---------------------------------------------------------------------------
// Existing-file parsing
// ---------------------------------------------------------------------------

interface FileSection {
  id: string;
  version: string;
  body: string;
}

interface UserSegment {
  content: string;
  afterId: string | null;
  beforeId: string | null;
}

interface ParsedFile {
  eol: '\n' | '\r\n';
  bom: boolean;
  meta: { template: string | null; version: string; sections: string[] } | null;
  sections: FileSection[];
  preMeta: string[];
  segments: UserSegment[];
  warnings: string[];
}

function parseMetaAttrs(attrs: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const m of attrs.matchAll(/(\w+)="([^"]*)"/g)) out[m[1]] = m[2];
  return out;
}

function parseFile(raw: string): ParsedFile {
  const bom = raw.charCodeAt(0) === 0xfeff;
  const content = bom ? raw.slice(1) : raw;
  const eol: '\n' | '\r\n' = content.includes('\r\n') ? '\r\n' : '\n';
  const lines = content.replace(/\r\n/g, '\n').split('\n');

  const result: ParsedFile = {
    eol,
    bom,
    meta: null,
    sections: [],
    preMeta: [],
    segments: [],
    warnings: [],
  };

  const metaIndex = lines.findIndex(l => META_RE.test(l));
  if (metaIndex >= 0) {
    const attrs = parseMetaAttrs(lines[metaIndex].match(META_RE)![1]);
    result.meta = {
      template: attrs.template ?? null,
      version: attrs.version ?? 'unknown',
      sections: (attrs.sections ?? '').split(',').map(s => s.trim()).filter(Boolean),
    };
  }

  const seen = new Set<string>();
  let buffer: string[] = [];
  let bufferStart = 0;
  let lastId: string | null = null;

  const flush = (beforeId: string | null): void => {
    const text = buffer.join('\n').trim();
    if (text) {
      if (metaIndex >= 0 && bufferStart < metaIndex) result.preMeta.push(text);
      else result.segments.push({ content: text, afterId: lastId, beforeId });
    }
    buffer = [];
  };

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    if (META_RE.test(line)) {
      if (i === metaIndex) {
        flush(null);
        bufferStart = i + 1;
      } else {
        result.warnings.push('Removed duplicate SW:META line');
      }
      continue;
    }

    const start = line.match(START_RE);
    if (start) {
      const id = start[1];
      let end = -1;
      for (let j = i + 1; j < lines.length; j++) {
        if (START_RE.test(lines[j])) break;
        const e = lines[j].match(END_RE);
        if (e && e[1] === id) {
          end = j;
          break;
        }
      }
      if (end < 0) {
        result.warnings.push(`Repaired unterminated marker for section "${id}" (its text was kept as user content)`);
        continue; // drop the marker line, keep the body as user content
      }
      if (seen.has(id)) {
        result.warnings.push(`Removed duplicate section "${id}"`);
        i = end;
        continue;
      }
      seen.add(id);
      flush(id);
      result.sections.push({ id, version: start[2] ?? '', body: lines.slice(i + 1, end).join('\n').trim() });
      lastId = id;
      i = end;
      bufferStart = i + 1;
      continue;
    }

    if (END_RE.test(line)) {
      result.warnings.push(`Removed stray end marker "${line.trim()}"`);
      continue;
    }

    if (buffer.length === 0) bufferStart = i;
    buffer.push(line);
  }
  flush(null);

  return result;
}

// ---------------------------------------------------------------------------
// User-content cleanup
// ---------------------------------------------------------------------------

/** Remove "↓ ORIGINAL ↓" / "↓ PROJECT-SPECIFIC ↓" markers and their leading rules. */
function stripLegacyMarkers(text: string): { text: string; found: boolean } {
  const lines = text.split('\n');
  const out: string[] = [];
  let found = false;
  for (const line of lines) {
    if (LEGACY_MARKER_RE.test(line)) {
      found = true;
      while (out.length && (HR_RE.test(out[out.length - 1]) || out[out.length - 1].trim() === '')) out.pop();
      continue;
    }
    out.push(line);
  }
  return { text: out.join('\n').trim(), found };
}

interface Block {
  heading: string | null;
  /** Heading level (1 or 2); meaningless when `heading` is null. */
  level: 1 | 2;
  lines: string[];
}

/**
 * Split markdown into heading blocks. BOTH `#` and `##` start a new block, so a
 * user's own H1 that follows a 1.x template section is never swallowed when
 * that section is stripped.
 */
function splitBlocks(text: string): Block[] {
  const blocks: Block[] = [];
  let cur: Block = { heading: null, level: 2, lines: [] };
  let inFence = false;
  for (const line of text.split('\n')) {
    if (FENCE_RE.test(line)) inFence = !inFence;
    if (!inFence && (H2_RE.test(line) || H1_RE.test(line))) {
      const level: 1 | 2 = H2_RE.test(line) ? 2 : 1;
      blocks.push(cur);
      cur = {
        heading: line.slice(level + 1).replace(/\s*\{#[^}]*\}\s*$/, '').trim(),
        level,
        lines: [],
      };
      continue;
    }
    cur.lines.push(line);
  }
  blocks.push(cur);
  return blocks.filter(b => b.heading !== null || b.lines.some(l => l.trim()));
}

function joinBlocks(blocks: Block[]): string {
  return blocks
    .map(b =>
      (b.heading === null
        ? b.lines.join('\n')
        : ['#'.repeat(b.level) + ' ' + b.heading, ...b.lines].join('\n')
      ).trim()
    )
    .filter(Boolean)
    .join('\n\n');
}

/** Drop raw template copies (`<!-- SECTION:x --> … <!-- /SECTION -->`) and 1.x no-heading lines. */
function stripLegacyLines(text: string, projectName: string): string {
  const out: string[] = [];
  let inTemplate = false;
  let inFence = false;
  for (const line of text.split('\n')) {
    if (FENCE_RE.test(line)) inFence = !inFence;
    if (inFence) {
      if (!inTemplate) out.push(line);
      continue;
    }
    if (TEMPLATE_START_RE.test(line)) {
      inTemplate = true;
      continue;
    }
    if (TEMPLATE_END_RE.test(line)) {
      inTemplate = false;
      continue;
    }
    if (inTemplate) continue;
    if (LEGACY_LINE_RES.some(re => re.test(line))) continue;
    if (H1_RE.test(line)) {
      const title = line.slice(2).trim();
      if (title === projectName || title === '{PROJECT_NAME}') continue;
    }
    out.push(line);
  }
  return out.join('\n');
}

/** Strip known 1.x template H2 blocks; keep everything else verbatim. */
function stripLegacyBlocks(text: string, type: TemplateType, projectName: string): string {
  const known = LEGACY_HEADINGS[type];
  const blocks = splitBlocks(stripLegacyLines(text, projectName));
  const kept: Block[] = [];
  for (const b of blocks) {
    if (b.heading === null || b.level !== 2) {
      kept.push(b);
      continue;
    }
    if (b.heading === SKILL_MEMORIES_HEADING) {
      const lines = b.lines.filter(l => !SKILL_MEMORIES_BOILERPLATE.some(re => re.test(l)));
      const hasContent = lines.some(l => l.trim() && !l.trim().startsWith('<!--'));
      if (hasContent) kept.push({ heading: b.heading, level: b.level, lines });
      continue;
    }
    const sigs = known[b.heading];
    if (sigs) {
      const body = b.lines.join('\n');
      if (sigs.length === 0 || sigs.some(s => body.includes(s))) continue;
    }
    kept.push(b);
  }
  return tidyRules(joinBlocks(kept));
}

/** Collapse rules left behind by removed blocks: no leading/trailing/consecutive `---`. */
function tidyRules(text: string): string {
  const lines = text.split('\n');
  const out: string[] = [];
  for (const line of lines) {
    if (HR_RE.test(line)) {
      const prev = [...out].reverse().find(l => l.trim() !== '');
      if (prev === undefined || HR_RE.test(prev)) continue;
    }
    out.push(line);
  }
  while (out.length && (HR_RE.test(out[out.length - 1]) || out[out.length - 1].trim() === '')) out.pop();
  return out.join('\n').trim();
}

function normalizeKey(text: string): string {
  return text.replace(/\s+/g, ' ').trim().toLowerCase();
}

/**
 * Drop H2 blocks that repeat an earlier identical block (ORIGINAL stacking
 * artifact). Returns one entry per input (possibly empty) so callers keep
 * their positional metadata.
 */
function dedupeBlocks(texts: string[]): string[] {
  const seen = new Set<string>();
  return texts.map(text => {
    const kept: Block[] = [];
    for (const b of splitBlocks(text)) {
      const key = normalizeKey(joinBlocks([b]));
      if (!key || seen.has(key)) continue;
      seen.add(key);
      kept.push(b);
    }
    return joinBlocks(kept);
  });
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

function wrap(id: string, body: string, version: string): string {
  return `<!-- SW:SECTION:${id} version="${version}" -->\n${body}\n<!-- SW:END:${id} -->`;
}

function genMeta(type: TemplateType, version: string, ids: string[]): string {
  return `<!-- SW:META template="${type}" version="${version}" sections="${ids.join(',')}" -->`;
}

function fillName(text: string, name: string): string {
  return text.replace(/\{PROJECT_NAME\}/g, name);
}

const PLACEHOLDERS: Array<{ key: string; label: string; pick: (c: StackCommands) => string | undefined }> = [
  { key: 'BUILD_CMD', label: 'build', pick: c => c.build },
  { key: 'TEST_CMD', label: 'test', pick: c => c.test },
  { key: 'LINT_CMD', label: 'lint', pick: c => c.lint },
];

function todoComment(label: string): string {
  return `<!-- TODO: add ${label} command -->`;
}

/**
 * Fill `{{BUILD_CMD}}` / `{{TEST_CMD}}` / `{{LINT_CMD}}` (and the TODO comment a
 * previous run may have left) only where they are still present.
 */
export function fillCommandPlaceholders(text: string, commands?: StackCommands): string {
  let out = text;
  for (const p of PLACEHOLDERS) {
    const value = commands ? p.pick(commands) : undefined;
    const token = `{{${p.key}}}`;
    const todo = todoComment(p.label);
    if (!out.includes(token) && !out.includes(todo)) continue;
    const replacement = value ? '`' + value + '`' : todo;
    out = out.split('`' + token + '`').join(replacement);
    out = out.split(token).join(value ?? todo);
    if (value) out = out.split(todo).join('`' + value + '`');
  }
  return out;
}

function majorOf(version: string): number {
  const m = version.match(/^(\d+)/);
  return m ? Number(m[1]) : 0;
}

function normalizeTemplate(secs: TemplateSection[] | ParsedTemplate, opts?: MergeOptions): ParsedTemplate {
  if (Array.isArray(secs)) {
    return { sections: [...secs].sort((a, b) => a.order - b.order), tail: opts?.tail ?? '' };
  }
  return { sections: [...secs.sections].sort((a, b) => a.order - b.order), tail: secs.tail };
}

function finish(text: string, p: ParsedFile | null): string {
  let out = text.trim() + '\n';
  if (p?.eol === '\r\n') out = out.replace(/\n/g, '\r\n');
  if (p?.bom) out = '\uFEFF' + out;
  return out;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function mergeInstructionFile(
  existing: string | null,
  secs: TemplateSection[] | ParsedTemplate,
  type: TemplateType,
  ver: string,
  name: string,
  opts: MergeOptions = {}
): MergeResult {
  const tpl = normalizeTemplate(secs, opts);
  const ids = tpl.sections.map(s => s.id);

  if (!existing || !existing.trim()) {
    const parts = [genMeta(type, ver, ids)];
    for (const s of tpl.sections) parts.push(wrap(s.id, fillName(s.content, name), ver));
    if (tpl.tail) parts.push(fillName(tpl.tail, name));
    return {
      content: finish(fillCommandPlaceholders(parts.join('\n\n'), opts.commands), null),
      action: 'created',
      updated: [],
      added: ids,
      removed: [],
      preserved: 0,
      warnings: [],
      migration: null,
    };
  }

  const p = parseFile(existing);
  const warnings = [...p.warnings];
  const legacy = p.meta === null && p.sections.length === 0;
  const fromVersion = p.meta?.version ?? p.sections[0]?.version ?? 'unknown';
  const migrating = legacy || majorOf(fromVersion) < TEMPLATE_SCHEMA_MAJOR;

  // --- classify sections -------------------------------------------------
  const fileById = new Map(p.sections.map(s => [s.id, s]));
  const listed = new Set(p.meta?.sections ?? p.sections.map(s => s.id));
  const rendered: FileSection[] = [];
  const updated: string[] = [];
  const added: string[] = [];
  const skipped: string[] = [];

  for (const s of tpl.sections) {
    const body = fillName(s.content, name);
    const cur = fileById.get(s.id);
    if (cur) {
      if (cur.body === body) rendered.push({ id: s.id, version: cur.version || ver, body });
      else {
        rendered.push({ id: s.id, version: ver, body });
        updated.push(s.id);
      }
    } else if (listed.has(s.id) && !s.required) {
      skipped.push(s.id);
    } else {
      rendered.push({ id: s.id, version: ver, body });
      added.push(s.id);
    }
  }
  const tplIds = new Set(ids);
  const removed = p.sections.map(s => s.id).filter(id => !tplIds.has(id));
  const renderedIds = rendered.map(r => r.id);
  const sectionsChanged =
    updated.length > 0 ||
    added.length > 0 ||
    removed.length > 0 ||
    renderedIds.join(',') !== (p.meta?.sections ?? []).join(',');
  const metaVersion = !p.meta || sectionsChanged || migrating ? ver : p.meta.version;

  // --- classify user content ----------------------------------------------
  let legacyMarkers = false;
  const clean = (text: string): string => {
    const r = stripLegacyMarkers(text);
    legacyMarkers = legacyMarkers || r.found;
    return r.text;
  };
  let pre = p.preMeta.map(clean).filter(Boolean);
  let segs = p.segments.map(s => ({ ...s, content: clean(s.content) })).filter(s => s.content);

  if (migrating) {
    pre = pre.map(t => stripLegacyBlocks(t, type, name)).filter(Boolean);
    segs = segs.map(s => ({ ...s, content: stripLegacyBlocks(s.content, type, name) })).filter(s => s.content);
  }
  if (migrating || legacyMarkers) {
    const deduped = dedupeBlocks([...pre, ...segs.map(s => s.content)]);
    const preCount = pre.length;
    pre = deduped.slice(0, preCount).filter(Boolean);
    segs = segs.map((s, i) => ({ ...s, content: deduped[preCount + i] })).filter(s => s.content);
  }

  const attached = new Map<string, string[]>();
  const post: string[] = [];
  const surviving = new Set(renderedIds);
  for (const s of segs) {
    if (!migrating && s.afterId && surviving.has(s.afterId)) {
      const list = attached.get(s.afterId) ?? [];
      list.push(s.content);
      attached.set(s.afterId, list);
    } else {
      post.push(s.content);
    }
  }

  const userText = [...pre, ...segs.map(s => s.content)].join('\n');
  const hasCommands = /^## Commands\s*$/m.test(userText);
  const addTail = migrating && Boolean(tpl.tail) && !hasCommands;

  // --- render --------------------------------------------------------------
  const parts: string[] = [];
  if (pre.length) parts.push(pre.join('\n\n'));
  parts.push(genMeta(type, metaVersion, renderedIds));
  for (const r of rendered) {
    parts.push(wrap(r.id, r.body, r.version));
    for (const a of attached.get(r.id) ?? []) parts.push(a);
  }
  if (addTail) parts.push(fillName(tpl.tail, name));
  parts.push(...post);

  const content = finish(fillCommandPlaceholders(parts.join('\n\n'), opts.commands), p);
  const preserved = pre.length + segs.length;

  if (skipped.length) warnings.push(`Skipped optional sections you removed earlier: ${skipped.join(', ')}`);

  let migration: MigrationInfo | null = null;
  if (migrating && (legacy || removed.length > 0)) {
    migration = { fromVersion: legacy ? 'legacy (no markers)' : fromVersion, removed };
    warnings.push(
      `Upgraded instructions from ${migration.fromVersion} to ${ver}: ` +
        (removed.length ? `removed 1.x sections ${removed.join(', ')}; ` : 'stripped 1.x template blocks; ') +
        'your own notes were kept below the managed block.'
    );
  }

  if (content === existing) {
    return { content, action: 'unchanged', updated: [], added: [], removed: [], preserved, warnings, migration: null };
  }

  return { content, action: 'merged', updated, added, removed, preserved, warnings, migration };
}

/**
 * Strip all SW-managed content from an instruction file, returning only user
 * content (null when nothing is left). Used by `specweave uninstall`.
 */
export function stripSwSections(content: string): string | null {
  if (!content || !content.trim()) return null;
  const p = parseFile(content);
  if (p.meta === null && p.sections.length === 0) return content.trim() || null;
  const parts = [...p.preMeta, ...p.segments.map(s => s.content)]
    .map(t => stripLegacyMarkers(t).text)
    .filter(Boolean);
  return parts.length ? parts.join('\n\n') : null;
}

/**
 * Read specweave's own package.json (not the user's project).
 * Resolves reliably with symlinked installs (nvm, pnpm, npm link); falls back to a directory walk.
 */
export function readSpecweavePackageJson(): Record<string, any> {
  try {
    const require = createRequire(import.meta.url);
    const pkgPath = require.resolve('specweave/package.json');
    return JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
  } catch {
    // fall back to a directory walk (npm link, running from a checkout)
  }
  try {
    let d = path.dirname(fileURLToPath(import.meta.url));
    for (let i = 0; i < 10; i++) {
      const p = path.join(d, 'package.json');
      if (fs.existsSync(p)) {
        const j = JSON.parse(fs.readFileSync(p, 'utf-8'));
        if (j.name === 'specweave') return j;
      }
      const parent = path.dirname(d);
      if (parent === d) break;
      d = parent;
    }
  } catch {
    // ignore
  }
  return {};
}

export function getPackageVersion(): string {
  return readSpecweavePackageJson().version ?? '0.0.0';
}

/**
 * Minimum Node.js version from specweave's package.json `engines.node` (e.g. ">=20.12.0" → "20.12.0").
 */
export function getMinNodeVersion(): string {
  const engines = readSpecweavePackageJson().engines?.node;
  const m = typeof engines === 'string' ? engines.match(/(\d+)(?:\.(\d+))?(?:\.(\d+))?/) : null;
  if (!m) return '20.0.0';
  return `${m[1]}.${m[2] ?? '0'}.${m[3] ?? '0'}`;
}
