#!/usr/bin/env ts-node
/**
 * Initialize MEMORY.md files for all skills
 *
 * Creates MEMORY.md from template for any skill that doesn't have one yet.
 * Skips skills that already have MEMORY.md to preserve existing learnings.
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Path to skills directory
const skillsPath = path.join(__dirname, '..', 'plugins', 'specweave', 'skills');

// Template content
const getTemplate = (skillName: string): string => {
  const timestamp = new Date().toISOString();
  return `# Skill Memory: ${skillName}

> Auto-generated by SpecWeave Reflect v4.0
> Last updated: ${timestamp}
> Skill: ${skillName}

## Learned Patterns

`;
};

async function initSkillMemory() {
  if (!fs.existsSync(skillsPath)) {
    console.error(`Skills directory not found: ${skillsPath}`);
    process.exit(1);
  }

  const skillDirs = fs.readdirSync(skillsPath, { withFileTypes: true });
  let created = 0;
  let skipped = 0;

  for (const dir of skillDirs) {
    if (!dir.isDirectory()) continue;

    const skillPath = path.join(skillsPath, dir.name);
    const memoryPath = path.join(skillPath, 'MEMORY.md');

    if (fs.existsSync(memoryPath)) {
      console.log(`✓ Skipping ${dir.name} (MEMORY.md already exists)`);
      skipped++;
      continue;
    }

    try {
      const content = getTemplate(dir.name);
      fs.writeFileSync(memoryPath, content, 'utf-8');
      console.log(`✓ Created MEMORY.md for ${dir.name}`);
      created++;
    } catch (error) {
      console.error(`✗ Failed to create MEMORY.md for ${dir.name}:`, error);
    }
  }

  console.log(`\nSummary:`);
  console.log(`  Created: ${created}`);
  console.log(`  Skipped: ${skipped}`);
  console.log(`  Total:   ${created + skipped}`);
}

initSkillMemory().catch(console.error);
