artifact_location: /Users/antonabyzov/Projects/github/specweave/runs/mlflow/120964265307288393
creation_time: 1762282444441
experiment_id: '120964265307288393'
last_update_time: 1762282444441
lifecycle_stage: active
name: /Users/antonabyzov/Projects/github/specweave/.specweave/test-runs/ml-pipeline/2025-11-04T18-53-52-290Z
