artifact_uri: /Users/antonabyzov/Projects/github/specweave/runs/mlflow/117986000268436421/cfdaaf4324fa48b881c51f2525bb4210/artifacts
end_time: 1762277310039
entry_point_name: ''
experiment_id: '117986000268436421'
lifecycle_stage: active
run_id: cfdaaf4324fa48b881c51f2525bb4210
run_name: train
source_name: ''
source_type: 4
source_version: ''
start_time: 1762277304566
status: 3
tags: []
user_id: antonabyzov
