/**
 * Skill Memory Merger Unit Tests
 *
 * Tests memory file parsing, generation, deduplication, and merging.
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';

// Import types and functions
import {
  parseMemoryFile,
  generateMemoryContent,
  areLearningsDuplicate,
  mergeMemoryFiles,
  addLearning,
  removeLearning,
  readMemoryFile,
  writeMemoryFile,
  createEmptyMemory,
  type Learning,
  type MemoryFile,
} from '../../../../src/core/reflection/skill-memory-merger.js';

describe('skill-memory-merger', () => {
  let testDir: string;

  beforeEach(() => {
    testDir = fs.mkdtempSync(path.join(os.tmpdir(), 'merger-test-'));
  });

  afterEach(() => {
    fs.rmSync(testDir, { recursive: true, force: true });
  });

  describe('parseMemoryFile', () => {
    it('should parse valid memory file content', () => {
      // Use the actual format from the implementation:
      // #### LRN-XXX (High Confidence)
      // **Context**: ...
      // **Learning**: ...
      // **Triggers**: ...
      // **Added**: ...
      const content = `# Frontend Memory

> Auto-generated by SpecWeave Reflect. User learnings are preserved across updates.
> Last updated: 2026-01-06T10:00:00Z

## Learned Patterns

#### LRN-20260106-ABCD (High Confidence)
**Context**: User corrected button usage
**Learning**: Use Button from design system
**Triggers**: button, component, ui
**Added**: 2026-01-06
**Source**: session:2026-01-06
`;

      const result = parseMemoryFile(content);

      expect(result).not.toBeNull();
      expect(result.skillName).toBe('frontend');
      expect(result.learnings).toHaveLength(1);
      expect(result.learnings[0].id).toBe('LRN-20260106-ABCD');
      expect(result.learnings[0].confidence).toBe('high');
      expect(result.learnings[0].content).toBe('Use Button from design system');
      expect(result.learnings[0].triggers).toContain('button');
    });

    it('should parse multiple learnings', () => {
      const content = `# Testing Memory

> Auto-generated by SpecWeave Reflect. User learnings are preserved across updates.
> Last updated: 2026-01-06T10:00:00Z

## Learned Patterns

#### LRN-20260106-0001 (High Confidence)
**Learning**: Use vi.fn() not jest.fn()
**Triggers**: mock, vitest
**Added**: 2026-01-06
**Source**: session:2026-01-06

#### LRN-20260105-0002 (Medium Confidence)
**Learning**: Always use describe blocks
**Triggers**: test, structure
**Added**: 2026-01-05
**Source**: session:2026-01-05
`;

      const result = parseMemoryFile(content);

      expect(result.learnings).toHaveLength(2);
      expect(result.learnings[0].id).toBe('LRN-20260106-0001');
      expect(result.learnings[1].id).toBe('LRN-20260105-0002');
      expect(result.learnings[1].confidence).toBe('medium');
    });

    it('should return memory object for empty content', () => {
      // Implementation returns a MemoryFile even for empty content
      const result = parseMemoryFile('');
      expect(result).toBeDefined();
      expect(result.learnings).toEqual([]);
    });

    it('should handle missing optional fields', () => {
      const content = `# Frontend Memory

## Learned Patterns

#### LRN-20260106-ABCD (High Confidence)
**Learning**: Some learning
**Added**: 2026-01-06
`;

      const result = parseMemoryFile(content);

      expect(result).not.toBeNull();
      expect(result.learnings[0].context).toBeUndefined();
      // triggers is optional - when not provided in MEMORY.md, it's undefined
      expect(result.learnings[0].triggers).toBeUndefined();
    });
  });

  describe('generateMemoryContent', () => {
    it('should generate valid markdown content', () => {
      const memory: MemoryFile = {
        skillName: 'frontend',
        lastUpdated: '2026-01-06T10:00:00Z',
        learnings: [
          {
            id: 'LRN-20260106-ABCD',
            timestamp: '2026-01-06T10:00:00Z',
            type: 'correction',
            confidence: 'high',
            content: 'Use Button from design system',
            context: 'User corrected button usage',
            triggers: ['button', 'component'],
            source: 'session:2026-01-06',
          },
        ],
      };

      const content = generateMemoryContent(memory);

      expect(content).toContain('# Frontend Memory');
      expect(content).toContain('> Auto-generated by SpecWeave Reflect');
      expect(content).toContain('#### LRN-20260106-ABCD (High Confidence)');
      expect(content).toContain('**Learning**: Use Button from design system');
      expect(content).toContain('**Context**: User corrected button usage');
      expect(content).toContain('**Triggers**: button, component');
    });

    it('should handle empty learnings array', () => {
      const memory: MemoryFile = {
        skillName: 'testing',
        lastUpdated: '2026-01-06T10:00:00Z',
        learnings: [],
      };

      const content = generateMemoryContent(memory);

      expect(content).toContain('# Testing Memory');
      // Should not have any learning entries
      expect(content).not.toContain('#### LRN-');
    });
  });

  describe('areLearningsDuplicate', () => {
    it('should detect same ID as duplicate', () => {
      const learning1: Learning = {
        id: 'LRN-20260106-ABCD',
        timestamp: '2026-01-06T10:00:00Z',
        type: 'correction',
        confidence: 'high',
        content: 'Learning A',
        triggers: ['a'],
        source: 'session',
      };
      const learning2: Learning = {
        id: 'LRN-20260106-ABCD',
        timestamp: '2026-01-07T10:00:00Z',
        type: 'rule',
        confidence: 'medium',
        content: 'Learning B',
        triggers: ['b'],
        source: 'session',
      };

      expect(areLearningsDuplicate(learning1, learning2)).toBe(true);
    });

    it('should detect content substring as duplicate', () => {
      const learning1: Learning = {
        id: 'LRN-001',
        timestamp: '2026-01-06T10:00:00Z',
        type: 'correction',
        confidence: 'high',
        content: 'Always use Button component from design system',
        triggers: ['button'],
        source: 'session',
      };
      const learning2: Learning = {
        id: 'LRN-002',
        timestamp: '2026-01-07T10:00:00Z',
        type: 'correction',
        confidence: 'high',
        content: 'Use Button component from design system for all buttons',
        triggers: ['button'],
        source: 'session',
      };

      expect(areLearningsDuplicate(learning1, learning2)).toBe(true);
    });

    it('should detect high trigger overlap as duplicate', () => {
      const learning1: Learning = {
        id: 'LRN-001',
        timestamp: '2026-01-06T10:00:00Z',
        type: 'correction',
        confidence: 'high',
        content: 'Learning about buttons',
        triggers: ['button', 'component', 'ui', 'style'],
        source: 'session',
      };
      const learning2: Learning = {
        id: 'LRN-002',
        timestamp: '2026-01-07T10:00:00Z',
        type: 'correction',
        confidence: 'high',
        content: 'Different learning about buttons',
        triggers: ['button', 'component', 'ui', 'design'],
        source: 'session',
      };

      // 3/4 = 75% overlap, above 50% threshold
      expect(areLearningsDuplicate(learning1, learning2)).toBe(true);
    });

    it('should not detect different learnings as duplicate', () => {
      const learning1: Learning = {
        id: 'LRN-001',
        timestamp: '2026-01-06T10:00:00Z',
        type: 'correction',
        confidence: 'high',
        content: 'Use vi.fn() for mocks',
        triggers: ['mock', 'vitest', 'test'],
        source: 'session',
      };
      const learning2: Learning = {
        id: 'LRN-002',
        timestamp: '2026-01-07T10:00:00Z',
        type: 'correction',
        confidence: 'high',
        content: 'Use Button from design system',
        triggers: ['button', 'component', 'ui'],
        source: 'session',
      };

      expect(areLearningsDuplicate(learning1, learning2)).toBe(false);
    });
  });

  describe('mergeMemoryFiles', () => {
    it('should return user memory when default is null', () => {
      const userMemory: MemoryFile = {
        skillName: 'frontend',
        lastUpdated: '2026-01-06T10:00:00Z',
        learnings: [
          {
            id: 'LRN-001',
            timestamp: '2026-01-06T10:00:00Z',
            type: 'correction',
            confidence: 'high',
            content: 'User learning',
            triggers: ['user'],
            source: 'session',
          },
        ],
      };

      const result = mergeMemoryFiles(userMemory, null);

      expect(result.success).toBe(true);
      expect(result.preserved).toBe(1);
      expect(result.added).toBe(0);
    });

    it('should return default memory when user is null', () => {
      const defaultMemory: MemoryFile = {
        skillName: 'frontend',
        lastUpdated: '2026-01-06T10:00:00Z',
        learnings: [
          {
            id: 'LRN-001',
            timestamp: '2026-01-06T10:00:00Z',
            type: 'rule',
            confidence: 'high',
            content: 'Default learning',
            triggers: ['default'],
            source: 'default',
          },
        ],
      };

      const result = mergeMemoryFiles(null, defaultMemory);

      expect(result.success).toBe(true);
      expect(result.preserved).toBe(0);
      expect(result.added).toBe(1);
    });

    it('should merge unique learnings from both', () => {
      const userMemory: MemoryFile = {
        skillName: 'frontend',
        lastUpdated: '2026-01-06T10:00:00Z',
        learnings: [
          {
            id: 'LRN-USER-001',
            timestamp: '2026-01-06T10:00:00Z',
            type: 'correction',
            confidence: 'high',
            content: 'User learning about buttons unique content',
            triggers: ['button'],
            source: 'session',
          },
        ],
      };

      const defaultMemory: MemoryFile = {
        skillName: 'frontend',
        lastUpdated: '2026-01-05T10:00:00Z',
        learnings: [
          {
            id: 'LRN-DEFAULT-001',
            timestamp: '2026-01-05T10:00:00Z',
            type: 'rule',
            confidence: 'high',
            content: 'Default learning about forms totally different',
            triggers: ['form'],
            source: 'default',
          },
        ],
      };

      const result = mergeMemoryFiles(userMemory, defaultMemory);

      expect(result.success).toBe(true);
      expect(result.preserved).toBe(1);
      expect(result.added).toBe(1);
      expect(result.deduped).toBe(0);
    });

    it('should deduplicate overlapping learnings', () => {
      const userMemory: MemoryFile = {
        skillName: 'frontend',
        lastUpdated: '2026-01-06T10:00:00Z',
        learnings: [
          {
            id: 'LRN-USER-001',
            timestamp: '2026-01-06T10:00:00Z',
            type: 'correction',
            confidence: 'high',
            content: 'Use Button from design system',
            triggers: ['button', 'component', 'ui'],
            source: 'session',
          },
        ],
      };

      const defaultMemory: MemoryFile = {
        skillName: 'frontend',
        lastUpdated: '2026-01-05T10:00:00Z',
        learnings: [
          {
            id: 'LRN-DEFAULT-001',
            timestamp: '2026-01-05T10:00:00Z',
            type: 'rule',
            confidence: 'high',
            content: 'Always use Button from design system for all buttons',
            triggers: ['button', 'component', 'design'],
            source: 'default',
          },
        ],
      };

      const result = mergeMemoryFiles(userMemory, defaultMemory);

      expect(result.success).toBe(true);
      expect(result.preserved).toBe(1);
      expect(result.added).toBe(0);
      expect(result.deduped).toBe(1);
    });

    it('should return empty result when both are null', () => {
      const result = mergeMemoryFiles(null, null);

      // Implementation returns success true with empty content
      expect(result.success).toBe(true);
      expect(result.content).toBe('');
    });
  });

  describe('addLearning', () => {
    it('should add new learning to memory', () => {
      const memory: MemoryFile = {
        skillName: 'frontend',
        lastUpdated: '2026-01-05T10:00:00Z',
        learnings: [],
      };

      const newLearning: Learning = {
        id: 'LRN-20260106-NEW',
        timestamp: '2026-01-06T10:00:00Z',
        type: 'correction',
        confidence: 'high',
        content: 'New learning',
        triggers: ['new'],
        source: 'session',
      };

      const result = addLearning(memory, newLearning);

      expect(result.added).toBe(true);
      expect(memory.learnings).toHaveLength(1);
      expect(memory.learnings[0].id).toBe('LRN-20260106-NEW');
    });

    it('should not add duplicate learning', () => {
      const existingLearning: Learning = {
        id: 'LRN-001',
        timestamp: '2026-01-05T10:00:00Z',
        type: 'correction',
        confidence: 'high',
        content: 'Existing learning',
        triggers: ['existing'],
        source: 'session',
      };

      const memory: MemoryFile = {
        skillName: 'frontend',
        lastUpdated: '2026-01-05T10:00:00Z',
        learnings: [existingLearning],
      };

      const duplicateLearning: Learning = {
        id: 'LRN-002',
        timestamp: '2026-01-06T10:00:00Z',
        type: 'correction',
        confidence: 'high',
        content: 'Existing learning with more words',
        triggers: ['existing'],
        source: 'session',
      };

      const result = addLearning(memory, duplicateLearning);

      expect(result.added).toBe(false);
      expect(result.reason).toContain('Duplicate');
      expect(memory.learnings).toHaveLength(1);
    });
  });

  describe('removeLearning', () => {
    it('should remove learning by ID', () => {
      const memory: MemoryFile = {
        skillName: 'frontend',
        lastUpdated: '2026-01-05T10:00:00Z',
        learnings: [
          {
            id: 'LRN-001',
            timestamp: '2026-01-05T10:00:00Z',
            type: 'correction',
            confidence: 'high',
            content: 'Learning to remove',
            triggers: [],
            source: 'session',
          },
          {
            id: 'LRN-002',
            timestamp: '2026-01-05T10:00:00Z',
            type: 'rule',
            confidence: 'medium',
            content: 'Learning to keep',
            triggers: [],
            source: 'session',
          },
        ],
      };

      const removed = removeLearning(memory, 'LRN-001');

      expect(removed).toBe(true);
      expect(memory.learnings).toHaveLength(1);
      expect(memory.learnings[0].id).toBe('LRN-002');
    });

    it('should return false when learning not found', () => {
      const memory: MemoryFile = {
        skillName: 'frontend',
        lastUpdated: '2026-01-05T10:00:00Z',
        learnings: [],
      };

      const removed = removeLearning(memory, 'LRN-NONEXISTENT');

      expect(removed).toBe(false);
    });
  });

  describe('readMemoryFile / writeMemoryFile', () => {
    it('should write and read memory file', () => {
      const memoryPath = path.join(testDir, 'MEMORY.md');
      const memory: MemoryFile = {
        skillName: 'testing',
        lastUpdated: '2026-01-06T10:00:00Z',
        learnings: [
          {
            id: 'LRN-001',
            timestamp: '2026-01-06T10:00:00Z',
            type: 'correction',
            confidence: 'high',
            content: 'Test learning',
            triggers: ['test'],
            source: 'session',
          },
        ],
      };

      writeMemoryFile(memoryPath, memory);
      const readBack = readMemoryFile(memoryPath);

      expect(readBack).not.toBeNull();
      expect(readBack!.skillName).toBe('testing');
      expect(readBack!.learnings).toHaveLength(1);
      expect(readBack!.learnings[0].id).toBe('LRN-001');
    });

    it('should return null for non-existent file', () => {
      const result = readMemoryFile(path.join(testDir, 'nonexistent.md'));
      expect(result).toBeNull();
    });
  });

  describe('createEmptyMemory', () => {
    it('should create empty memory for skill', () => {
      const memory = createEmptyMemory('frontend');

      expect(memory.skillName).toBe('frontend');
      expect(memory.learnings).toEqual([]);
      expect(memory.lastUpdated).toBeDefined();
    });
  });

  // GAP-010: Edge case tests for rate limiting and new features
  describe('rate limiting (GAP-007)', () => {
    it('should block learning when daily limit reached', async () => {
      // Dynamically import to get the rate limiting functions
      const { checkRateLimits, DEFAULT_RATE_LIMITS } = await import(
        '../../../../src/core/reflection/skill-memory-merger.js'
      );

      const now = new Date();
      const learnings: Learning[] = [];

      // Add learnings to exceed daily limit
      for (let i = 0; i < DEFAULT_RATE_LIMITS.maxPerDay; i++) {
        learnings.push({
          id: `LRN-${i}`,
          timestamp: now.toISOString(), // All today
          type: 'correction',
          confidence: 'high',
          content: `Learning ${i}`,
          triggers: [],
          source: 'session',
        });
      }

      const memory: MemoryFile = {
        skillName: 'test',
        lastUpdated: now.toISOString(),
        learnings,
      };

      const result = checkRateLimits(memory);

      expect(result.allowed).toBe(false);
      expect(result.reason).toContain('Daily limit');
    });

    it('should allow learning when within limits', async () => {
      const { checkRateLimits } = await import(
        '../../../../src/core/reflection/skill-memory-merger.js'
      );

      const memory: MemoryFile = {
        skillName: 'test',
        lastUpdated: new Date().toISOString(),
        learnings: [],
      };

      const result = checkRateLimits(memory);

      expect(result.allowed).toBe(true);
    });

    it('should block learning when total limit reached', async () => {
      const { checkRateLimits, DEFAULT_RATE_LIMITS } = await import(
        '../../../../src/core/reflection/skill-memory-merger.js'
      );

      const learnings: Learning[] = [];
      const oldDate = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000); // 30 days ago

      // Add learnings to exceed total limit (but not daily/weekly)
      for (let i = 0; i < DEFAULT_RATE_LIMITS.maxTotal; i++) {
        learnings.push({
          id: `LRN-${i}`,
          timestamp: oldDate.toISOString(),
          type: 'correction',
          confidence: 'high',
          content: `Old learning ${i}`,
          triggers: [],
          source: 'session',
        });
      }

      const memory: MemoryFile = {
        skillName: 'test',
        lastUpdated: new Date().toISOString(),
        learnings,
      };

      const result = checkRateLimits(memory);

      expect(result.allowed).toBe(false);
      expect(result.reason).toContain('Total limit');
    });
  });

  describe('edge cases', () => {
    it('should handle empty content in learning', () => {
      const content = `# Test Memory

> Auto-generated by SpecWeave Reflect. User learnings are preserved across updates.
> Last updated: 2026-01-06T10:00:00Z

## Learned Patterns

#### LRN-20260106-EDGE (Medium Confidence)
**Context**: Edge case
**Learning**:
**Added**: 2026-01-06
`;

      const result = parseMemoryFile(content);

      expect(result.learnings).toHaveLength(0); // Empty content should be skipped
    });

    it('should handle unicode in learning content', () => {
      const memory: MemoryFile = {
        skillName: 'i18n',
        lastUpdated: '2026-01-06T10:00:00Z',
        learnings: [
          {
            id: 'LRN-UNICODE',
            timestamp: '2026-01-06T10:00:00Z',
            type: 'correction',
            confidence: 'high',
            content: '使用 Button 组件而不是自定义按钮 🎨',
            triggers: ['button', 'chinese'],
            source: 'session',
          },
        ],
      };

      const generated = generateMemoryContent(memory);
      const parsed = parseMemoryFile(generated);

      expect(parsed.learnings[0].content).toContain('Button');
    });

    it('should handle very long learning content', () => {
      const longContent = 'A'.repeat(500);
      const memory: MemoryFile = {
        skillName: 'test',
        lastUpdated: '2026-01-06T10:00:00Z',
        learnings: [
          {
            id: 'LRN-LONG',
            timestamp: '2026-01-06T10:00:00Z',
            type: 'rule',
            confidence: 'high',
            content: longContent,
            triggers: ['long'],
            source: 'session',
          },
        ],
      };

      const generated = generateMemoryContent(memory);
      const parsed = parseMemoryFile(generated);

      expect(parsed.learnings[0].content).toBe(longContent);
    });

    it('should handle special characters in triggers', () => {
      const memory: MemoryFile = {
        skillName: 'test',
        lastUpdated: '2026-01-06T10:00:00Z',
        learnings: [
          {
            id: 'LRN-SPECIAL',
            timestamp: '2026-01-06T10:00:00Z',
            type: 'correction',
            confidence: 'high',
            content: 'Test with special triggers',
            triggers: ['c++', 'node.js', 'is-valid', '@scope/package'],
            source: 'session',
          },
        ],
      };

      const generated = generateMemoryContent(memory);

      expect(generated).toContain('c++');
      expect(generated).toContain('node.js');
      expect(generated).toContain('is-valid');
    });
  });
});
