import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * SpecWeave Internal Documentation Sidebars
 *
 * Maps the .specweave/docs/internal/ structure to Docusaurus navigation.
 *
 * Uses autogenerated approach to automatically create navigation from folder structure.
 */

const sidebars: SidebarsConfig = {
  // Strategy Sidebar - Auto-generate from strategy/ folder
  strategySidebar: [
    {
      type: 'autogenerated',
      dirName: 'strategy',
    },
  ],

  // Specs Sidebar - Auto-generate from specs/ folder
  specsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'specs',
    },
  ],

  // Architecture Sidebar - Auto-generate from architecture/ folder
  architectureSidebar: [
    {
      type: 'autogenerated',
      dirName: 'architecture',
    },
  ],

  // Delivery Sidebar - Auto-generate from delivery/ folder
  deliverySidebar: [
    {
      type: 'autogenerated',
      dirName: 'delivery',
    },
  ],

  // Operations Sidebar - Auto-generate from operations/ folder
  operationsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'operations',
    },
  ],

  // Governance Sidebar - Auto-generate from governance/ folder
  governanceSidebar: [
    {
      type: 'autogenerated',
      dirName: 'governance',
    },
  ],
};

export default sidebars;
