artifact_location: /Users/antonabyzov/Projects/github/specweave/runs/mlflow/901699173721470316
creation_time: 1762281032209
experiment_id: '901699173721470316'
last_update_time: 1762281032209
lifecycle_stage: active
name: /Users/antonabyzov/Projects/github/specweave/.specweave/test-runs/ml-pipeline/2025-11-04T18-30-20-381Z
