artifact_uri: /Users/antonabyzov/Projects/github/specweave/runs/mlflow/710263413426481409/d458ed47cd1e44318fbf0ad2a53f7b73/artifacts
end_time: 1762280799509
entry_point_name: ''
experiment_id: '710263413426481409'
lifecycle_stage: active
run_id: d458ed47cd1e44318fbf0ad2a53f7b73
run_name: train
source_name: ''
source_type: 4
source_version: ''
start_time: 1762280794303
status: 3
tags: []
user_id: antonabyzov
