artifact_location: /Users/antonabyzov/Projects/github/specweave/runs/mlflow/125202284780716382
creation_time: 1762282048644
experiment_id: '125202284780716382'
last_update_time: 1762282048644
lifecycle_stage: active
name: /Users/antonabyzov/Projects/github/specweave/.specweave/test-runs/ml-pipeline/2025-11-04T18-47-17-003Z
